### ISSUE TITLE
Crash while merging spiro points

### ISSUE THREAD

**Issue by EmilyDirsh** [fontforge/fontforge#1004]
Select spiro control points, Edit > Merge To Line, crash.

On Fedora 20

```
Program received signal SIGSEGV, Segmentation fault.
SPSelectPrevPoint (sp=0xdc1f50, state=state@entry=1) at charview.c:12934
12934       if( !sp->prev->from )
(gdb) bt
#0  SPSelectPrevPoint (sp=0xdc1f50, state=state@entry=1) at charview.c:12934
#1  0x00007ffff796e870 in _CVMergeToLine (elide=0, cv=0xa06660) at charview.c:8123
#2  CVMergeToLine (gw=<optimized out>, UNUSED_mi=<optimized out>, UNUSED_e=<optimized out>) at charview.c:8134
#3  0x00007ffff76621e2 in gmenu_mouse (m=<optimized out>, event=0x7fffffffbd70) at gmenu.c:1001
#4  0x00007ffff76626bb in gmenu_eh (w=0xdc21d0, ge=0x7fffffffbd70) at gmenu.c:1586
#5  0x00007ffff768aa01 in dispatchEvent (gdisp=gdisp@entry=0x8af5e0, event=event@entry=0x7fffffffbed0) at gxdraw.c:3502
#6  0x00007ffff768c3ca in GXDrawEventLoop (gd=0x8af5e0) at gxdraw.c:3601
#7  0x00007ffff7a8e3a2 in fontforge_main (argc=1, argv=<optimized out>) at startui.c:1265
#8  0x00007ffff1ab3d65 in __libc_start_main (main=0x400920 <main>, argc=1, argv=0x7fffffffe138, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe128) at libc-start.c:285
#9  0x0000000000400951 in _start ()
```

**Comment by jimbo1qaz** [comment]
I get crashes whenever merging multiple Spiro points. FontForge-2017-07-31-Windows-r2.exe
