### ISSUE TITLE
Mac crash dec 13 version

### ISSUE THREAD

**Issue by andreaslarsen** [fontforge/fontforge#2000]
Happens when pressing cmd+w to close an edit window
Freezes the app
OSX10.10

```
Script started on Tue Dec 16 12:15:43 2014
No entry for terminal type "xterm-256color";
using dumb terminal settings.
(lldb) command source -s 0 '/Applications/FontForge.app/Contents/MacOS/debug-script'
Executing commands in '/Applications/FontForge.app/Contents/MacOS/debug-script'.
(lldb) version
lldb-320.4.156
(lldb) script print sys.version
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/pydoc.py", line 201, in <module>
    _encoding = locale.getpreferredencoding()
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/locale.py", line 606, in getpreferredencoding
    return getdefaultlocale()[1]
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'pydoc' is not defined
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
(lldb) settings set frame-format "frame #${frame.index}: ${frame.pc}{ ${module.file.basename}`${function.name-with-args}{${function.pc-offset}}}{ at ${line.file.basename}:${line.number}}\n"
(lldb) target create /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
Current executable set to '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64).
(lldb) target select 0
Current targets:
* target #0: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge ( arch=x86_64-apple-macosx, platform=host )
(lldb) #run -SkipPythonInitFiles 
(lldb) # please type the run command to start FontForge
(lldb) #
(lldb) # run
(lldb) #
(lldb) [1G[2m(lldb) [22m[8Grun
Process 5930 launched: '/Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge' (x86_64)
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.

 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.

 Based on sources from 22:08 AEST 13-Dec-2014-ML-D.

 Based on source from git with hash: 90313622dde594bc760efdb326f7790c9beb3fc7

fontforge.hasUserInterface!

PyFF_onAppClosing() cnt:1

Fontconfig warning: ignoring UTF-8: not a valid region tag

SPLFirstVisitorFoundSoughtXY() 606.378320 66.278320 336.278320

SPLFirstVisitorFoundSoughtXY() 347.541406 104.558594 226.000000

SplineFontPieceMeal() going unhinted...

zsys_interface length: 0

num_interfaces: 1

DEBUG POINT A REACHED...

getting network setup...

   port: 5670 

   addr: 10.0.1.255 

binding beacon...1. local addr:10.0.1.255 

binding beacon... 0x107a34e28

binding beacon... port:5670 

binding beacon...2. local addr:0.0.0.0 

14-12-16 12:16:41 client beacon address: 0.0.0.0



CVDoUndo() undo:0x1050bd7f0 u->next:0x0

SCUndoAct() ut_state case, layer:1 sc:0x10231ecc0 scn:h scw:520 uw:520

error: libgdraw.5.dylib debug map object file '/Applications/FontForge.app/Contents/Resources/opt/local/var/////////////////////////////////////////////////////////////////////gdraw/.libs/libgdraw_la-gmenu.o' has changed (actual time is 0x548cab84, debug map time is 0x548c2cf4) since this executable was linked, file will be ignored
error: libgdraw.5.dylib debug map object file '/Applications/FontForge.app/Contents/Resources/opt/local/var/////////////////////////////////////////////////////////////////////gdraw/.libs/libgdraw_la-gdraw.o' has changed (actual time is 0x548cab7e, debug map time is 0x548c2cee) since this executable was linked, file will be ignored
Process 5930 stopped
* thread #1: tid = 0x5916b, 0x0000000100376a6a libgdraw.5.dylib`GMenuDestroy + 9, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x0000000100376a6a libgdraw.5.dylib`GMenuDestroy + 9
libgdraw.5.dylib`GMenuDestroy + 9:
-> 0x100376a6a:  movq   0x40(%rbx), %rdi
   0x100376a6e:  callq  0x10035bcb6               ; GDrawGetDisplayOfWindow
   0x100376a73:  movq   %rax, %rdi
   0x100376a76:  callq  0x10035c623               ; GDrawPointerUngrab
(lldb) [1G[2m(lldb) [22m[8G
```

**Comment by andreaslarsen** [comment]
The latest updates appears to be a lot more stable so I'll close this and reopen if the problem reappears

**Comment by davelab6** [comment]
Great! Thanks
