### ISSUE TITLE
Expand stroke bug

### ISSUE THREAD

**Issue by m93a** [fontforge/fontforge#2029]
How to reproduce:
- select an element
- click on Element → Expand Stroke
- set Main Stroke Width and Minor Stroke Width to zero
- hit Apply

What should happen:
- an error message should appear
- the Main and Minor Stroke Width values should be reverted to default

What happens:
- the app crashes
- all work is lost

**Comment by larsenwork** [comment]
Expand stroke bug 2

How to reproduce: 
* Element -> Expand Stroke
* Cancel (either press escape or the cancel button)

What happens:
* Crash

Gist of crash report: https://gist.github.com/larsenwork/73c58e60f44046f40a40

**Comment by jtanx** [comment]
The 'zero stroke width' segfault:

~~~~~
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff58e16cc in HideStrokePointsCircle (c=0x7ffffffc1760)
    at splinestroke.c:809
809		    if ( op->me.x==p->me.x && op->me.y==p->me.y )
(gdb) bt
#0  0x00007ffff58e16cc in HideStrokePointsCircle (c=0x7ffffffc1760)
    at splinestroke.c:809
#1  0x00007ffff58e2151 in FindStrokePointsCircle (ss=0x9fbcd0, 
    c=0x7ffffffc1760) at splinestroke.c:945
#2  0x00007ffff58f1c5e in SplineSet_Stroke (ss=0x9f9b10, c=0x7ffffffc1760, 
    order2=0) at splinestroke.c:3596
#3  0x00007ffff58f1d77 in SplineSets_Stroke (ss=0x9f9b10, c=0x7ffffffc1760, 
    order2=0) at splinestroke.c:3622
#4  0x00007ffff58f2264 in SplineSetStroke (ss=0x9f9b10, si=0x7ffffffc1950, 
    order2=0) at splinestroke.c:3685
#5  0x00007ffff78c4f29 in CVStrokeIt (_cv=0x9085e0, si=0x7ffffffc1950, 
    justapply=0) at cvstroke.c:84
#6  0x00007ffff78c5be2 in _Stroke_OK (sd=0x7ffff7d85960 <strokedlg>, isapply=0)
    at cvstroke.c:258
#7  0x00007ffff78c5ca0 in Stroke_OK (g=0x9e6f70, e=0x7ffffffc2ad0)
    at cvstroke.c:268
#8  0x00007ffff6800787 in GButtonInvoked (b=0x9e6f70, ev=0x7ffffffc2db0)
    at gbuttons.c:255
#9  0x00007ffff6801788 in gbutton_mouse (g=0x9e6f70, event=0x7ffffffc2db0)
    at gbuttons.c:483
#10 0x00007ffff680c544 in _GWidget_Container_eh (gw=0x9e3530, 
    event=0x7ffffffc2db0) at gcontainer.c:302
#11 0x00007ffff680e408 in _GWidget_TopLevel_eh (gw=0x9e3530, 
    event=0x7ffffffc2db0) at gcontainer.c:745
#12 0x00007ffff689679b in dispatchEvent (gdisp=0x69a710, event=0x7ffffffc2f60)
    at gxdraw.c:3296
#13 0x00007ffff6896985 in GXDrawProcessOneEvent (gdisp=0x69a710)
    at gxdraw.c:3328
#14 0x00007ffff6812d9f in GDrawProcessOneEvent (gdisp=0x69a710) at gdraw.c:771
#15 0x00007ffff78caf99 in MakeStrokeDlg (cv=0x9085e0, 
    strokeit=0x7ffff78c4db2 <CVStrokeIt>, si=0x0) at cvstroke.c:1001
#16 0x00007ffff78cb073 in CVStroke (cv=0x9085e0) at cvstroke.c:1015
#17 0x00007ffff7848234 in CVMenuStroke (gw=0x954bd0, UNUSED_mi=0x990e50, 
    UNUSED_e=0x7fffffffbda0) at charview.c:9727
#18 0x00007ffff684335b in gmenu_mouse (m=0x8a5aa0, event=0x7fffffffbda0)
    at gmenu.c:943
#19 0x00007ffff6845034 in gmenu_eh (w=0x9fac10, ge=0x7fffffffbda0)
    at gmenu.c:1378
#20 0x00007ffff680cdf5 in _GWidget_Container_eh (gw=0x9fac10, 
    event=0x7fffffffbda0) at gcontainer.c:403
#21 0x00007ffff680e408 in _GWidget_TopLevel_eh (gw=0x9fac10, 
    event=0x7fffffffbda0) at gcontainer.c:745
#22 0x00007ffff689679b in dispatchEvent (gdisp=0x69a710, event=0x7fffffffbf50)
    at gxdraw.c:3296
#23 0x00007ffff6896dee in GXDrawEventLoop (gd=0x69a710) at gxdraw.c:3404
#24 0x00007ffff6812f0a in GDrawEventLoop (gdisp=0x69a710) at gdraw.c:791
#25 0x00007ffff7a522b2 in fontforge_main (argc=1, argv=0x7fffffffe2a8)
    at startui.c:1382
#26 0x000000000040085c in main (argc=1, argv=0x7fffffffe2a8) at main.c:39
~~~~~

**Comment by jtanx** [comment]
There was a division by zero error since the stroke width was zero.
