### ISSUE TITLE
SCTickValidationState() segfault while undoing actions

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2056]
~~~
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5873333 in SCTickValidationState (
    sc=<error reading variable: Cannot access memory at address 0x7fffff7feff8>, 
    layer=<error reading variable: Cannot access memory at address 0x7fffff7feff4>)
    at splinechar.c:1844
1844	void SCTickValidationState(SplineChar *sc,int layer) {
(gdb) where
#0  0x00007ffff5873333 in SCTickValidationState (
    sc=<error reading variable: Cannot access memory at address 0x7fffff7feff8>, 
    layer=<error reading variable: Cannot access memory at address 0x7fffff7feff4>)
    at splinechar.c:1844
#1  0x00007ffff58733b6 in SCTickValidationState (sc=0x3530ff0, layer=1)
    at splinechar.c:1852
#2  0x00007ffff58733b6 in SCTickValidationState (sc=0x8a03a0, layer=1)
    at splinechar.c:1852
#3  0x00007ffff58733b6 in SCTickValidationState (sc=0x3530ff0, layer=1)
    at splinechar.c:1852
#4  0x00007ffff58733b6 in SCTickValidationState (sc=0x8a03a0, layer=1)
    at splinechar.c:1852
#5  0x00007ffff58733b6 in SCTickValidationState (sc=0x3530ff0, layer=1)
    at splinechar.c:1852
#6  0x00007ffff58733b6 in SCTickValidationState (sc=0x8a03a0, layer=1)
    at splinechar.c:1852
#7  0x00007ffff58733b6 in SCTickValidationState (sc=0x3530ff0, layer=1)
    at splinechar.c:1852
#8  0x00007ffff58733b6 in SCTickValidationState (sc=0x8a03a0, layer=1)
    at splinechar.c:1852
#9  0x00007ffff58733b6 in SCTickValidationState (sc=0x3530ff0, layer=1)
    at splinechar.c:1852
---Type <return> to continue, or q <return> to quit---q
~~~

Is spurious.

**Comment by davelab6** [comment]
@adrientetar does the spurious tag mean not reproducable?

**Comment by adrientetar** [comment]
Yes
