### ISSUE TITLE
UFO: support public.glyphOrder in lib.plist

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2161]

**Comment by pathumego** [comment]
FDK interpolation tools need `lib.plist` to be present, id love to see this soon :)

**Comment by davelab6** [comment]
@frank-trampe i heard from @pathumego today that he can't use FDK with out this :(

**Comment by pathumego** [comment]
Or can someone suggest a workaround..

**Comment by adrientetar** [comment]
> FDK interpolation tools need `lib.plist` to be present

What does it need inside lib.plist? this file is just a container for arbitrary app-specific data.

**Comment by davelab6** [comment]
@pathum can you detail the problem you had?

**Comment by davelab6** [comment]
I chatted with @frank-trampe and the result was: assuming @pathumego 's error is related to FDK needing `public.glyphOrder`, which I guess might be true if FDK uses the glyph order in some way... GIDs are a thing, and I don't recall glyph ordering in the ufo spec, while fontforge has GIDs that are used for ordering in Font View when you run "Encoding, Compact", so we guess FF should export that glyphordering. Frank noted importing might be challenging, since we would be over-riding the standard system, but might be possible....

**Comment by frank-trampe** [comment]
So I just thought about this a bit more, and I'm inclined to prefer the ordering from the glyph index over the one from public.glyphOrder when generating the native glyph indices (and thus the custom encoding). We could add a layer to the FontView logic that displays the glyphs in something other than native or encoded order, but it's not clear to me what the purpose of this attribute is anyway. @adrientetar, can you explain further?

**Comment by adrientetar** [comment]
It is an optional element of the ufo3 spec: http://unifiedfontobject.org/versions/ufo3/lib.html

**Comment by frank-trampe** [comment]
Yes. I see that. But what would you like to see it mean in FontForge?

**Comment by adrientetar** [comment]
Well generally when importing a UFO in FontForge it displays the glyphs in alphabetic order or sth., this key would store the order of the glyphs as shown in the program.  
What's the “ordering from the glyph index” you speak of? Is it another way of getting glyph order out of an UFO? I thought public.glyphOrder was generally the only way to store the order of the glyph and IIRC glyphsapp/robofont use that.

**Comment by frank-trampe** [comment]
We currently get the order from the contents of the foreground glyph directory.

**Comment by adrientetar** [comment]
Okay I can see it. But I think other editors use public.glyphOrder for that rather than layer-specific ordering, need to confirm.

**Comment by pathumego** [comment]
@davelab6 Yep its asking `public.glyphOrder`.

**Comment by frank-trampe** [comment]
@pathumego, I don't understand that comment. Would you clarify?

**Comment by adrientetar** [comment]
He says he was asking for support of public.glyphOrder (he originally said lib.plist instead which is too generic).

**Comment by frank-trampe** [comment]
We currently round-trip this correctly, right?

Is it really important to use it natively? It's certainly possible to support it, but I don't see why this is a high priority right now.

**Comment by pathumego** [comment]
@adrientetar @frank-trampe  Exactly. @adrientetar Im trying to use Interpolation tools in FDK and wonder if there is a way around? Since you have used FF generated UFO's with FDK

**Comment by frank-trampe** [comment]
@pathumego, I still don't think I understand what you're trying to do and what the specific problem is. Would you describe in detail what you are trying to do and what is going wrong?

**Comment by adrientetar** [comment]
The only interpolation I have performed so far was inside Robofont (using ScaleFast) so I think robofont provides this to the program, given that it is indeed needed. What error message do you get?

**Comment by adrientetar** [comment]
> I don't see why this is a high priority right now.

No big deal for me personally.

**Comment by pathumego** [comment]
@adrientetar this is what I get when I try with this 
https://github.com/adobe-type-tools/python-scripts/blob/master/FDK%20Extras/UFOInstanceGenerator.py

```
Reading 2 UFO files...
Generating 5 instances...

Light (1/5)
Traceback (most recent call last):
  File "a.py", line 858, in <module>
    run()
  File "a.py", line 846, in run
    makeInstance((i+1, totalInstances), ufoMasters, instancesList[i], outputDirPath, options)
  File "a.py", line 465, in makeInstance
    glyphOrder = ufoMasters[0].lib["public.glyphOrder"]
KeyError: 'public.glyphOrder'
```
@frank-trampe  I just have to find a working solution for interpolation. I couldn't make any FF generated UFO files work with prior mentioned script :/ So that kind of defeat the purpose of UFO support for me..

**Comment by pathumego** [comment]
CC @paarandika

**Comment by adrientetar** [comment]
So it’s Adobe that use that in their script – it’s not needed I think. Try to replace `for glyphName in glyphOrder:` with `for glyph in ufoInstance:` and then use `glyph.name` inside the loop instead of glyphName.

**Comment by adrientetar** [comment]
Or maybe use `ufoMasters[0]` instead of `ufoInstance` which may not not be completely populated at this point of the code.

**Comment by adrientetar** [comment]
Otherwise you have the mutatormath script: https://github.com/adobe-type-tools/afdko/blob/8ae13914cbbefed6ff17819928fb65d9713da62c/FDK/Tools/SharedData/FDKScripts/makeInstancesUFO.py 
Though I’m not sure whether it interpolates fea values.

**Comment by frank-trampe** [comment]
@pathumego, it seems that that script is just using the glyph order in order to know which glyphs exist. I think that this is not a good strategy as the specification guarantees neither that the glyph order exists nor that it references all glyphs nor that all glyphs that it references exist.

@miguelsousa?

**Comment by miguelsousa** [comment]
@frank-trampe the spec does not enforce the presence of `public.glyphOrder`, but many of our scripts require it and expect that all the glyphs in the font be listed in it.

**Comment by pathumego** [comment]
@frank-trampe I agree. And it is confusing too. Im looking at other available scripts @adrientetar suggested to get this done.

Anyway I think as @miguelsousa pointed out if majority FDK scripts require the  `public.glyphOrder` we might as well support it.

**Comment by davelab6** [comment]
I think supporting it is important for ufov3 support. Sounds like more and
more UFOv3 tools will make use of this data as its in the v3 spec

**Comment by frank-trampe** [comment]
FontForge supports the data and ought to round trip it successfully. FontForge is not mapping this ordering to any native data structure, and it is not clear how we would do this. We can't use it as the primary source/destination for anything because it is not guaranteed to exist.

We could generate the ordering in parallel with the glyph contents, but the specifics are difficult.
* If we generate the ordering when not already present, we may be adding file noise (output changes without user-commanded data changes).
* If we generate the ordering (from the native glyph ordering) when the ordering already exists, we may lose data (particularly entries for non-existent glyphs).

We could map the glyph order to the custom encoding. This would be complicated and possibly confusing and possibly in violation of the intended purpose either of the glyph ordering or the encoding.

How are other applications doing this?

**Comment by frank-trampe** [comment]
@miguelsousa, was this dependence on an optional, optionally complete value a temporary oversight, or was this a reasoned design decision? Have you encountered some situation in which using the glyph ordering makes something work that would not work using the foreground glyph index?

**Comment by miguelsousa** [comment]
@frank-trampe "foreground glyph index"? What is that?

**Comment by adrientetar** [comment]
I think he speaks of content.plist?

**Comment by adrientetar** [comment]
@frank-trampe So apparently public.glyphOrder serves to store the order shown in the font view, including non-existing glyphs that are displayed empty (what robofont calls template glyphs).

**Comment by pathumego** [comment]
@frank-trampe so what is the status of this :)

**Comment by frank-trampe** [comment]
This is not in the top ten on my FontForge to-do list right now, unfortunately, and other things keep jumping in.

**Comment by pathumego** [comment]
CC @paarandika @lpsandaruwan

**Comment by pathumego** [comment]
@frank-trampe Thanks!  Can you suggest any workaround for this? or direct @lpsandaruwan on how to approach to fix this?

**Comment by frank-trampe** [comment]
It might be best to write a script that copies the contents of the foreground glyph index into the glyph order space. One could then run that before passing the files to the Adobe kit.

**Comment by adrientetar** [comment]
It could otherwise be done in ufo.c

**Comment by pathumego** [comment]
Ok I will work with @lpsandaruwan on this. Thanks guys!

**Comment by adrientetar** [comment]
The dump should happen in `UFOOutputLib()` of ufo.c precisely.

**Comment by frank-trampe** [comment]
@adrientetar, a good patch for ufo.c would require a significant amount of effort and a universally accepted method for mapping, generating, and round tripping the data. The specific challenge is reconciling the need to generate and to extend the data in some cases and to preserve it in others. That's why I think that a purpose-specific script is more appropriate and easier done in this case.

**Comment by pathumego** [comment]
@adrientetar Do you think I can use Robofab to make the UFO's ready for FDK? 
My whole build process is depending on Glyphs at the moment to re export the UFO's to be compatible.

**Comment by n8willis** [comment]
This is still a problem; it actively prevents using several UFO-based tools to do important production tasks like interpolation and building chromatic fonts. Has there been any progress?

**Comment by probonopd** [comment]
Looks like I just ran into this issue tying to use the Adobe Font Development Kit for OpenType (AFDKO) to convert a FontForge-generated ufo to otf.

https://github.com/probonopd/font-leutkirch/issues/2

**Comment by probonopd** [comment]
> Or can someone suggest a workaround..

@frankrolf has written a few lines of Python to solve this: https://github.com/adobe-type-tools/afdko/issues/1130#issuecomment-623180851. Works well for me :+1:
