### ISSUE TITLE
Corruption of 1st field of ttflangnames

### ISSUE THREAD

**Issue by adrientetar** [fontforge/fontforge#2169]
When opening then closing SourceSansPro_0.ufo, stack guards are raised with an invalid free (more likely to be seen when keeping another font open so the program doesn't close). It might be an overrun on the first field of sf->names, I watched the functions that set sf->names and they seem to do their job so it might be something contiguous in memory that makes invalid accesses.

~~~
*** Error in `/usr/local/bin/fontforge': double free or corruption (fasttop): 0x00000000008867c0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff71d2e37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) where
#0  0x00007ffff71d2e37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff71d4528 in __GI_abort () at abort.c:89
#2  0x00007ffff7213f74 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff731cf00 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff721b586 in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff731d0c8 "double free or corruption (fasttop)", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0)
    at malloc.c:3840
#5  0x00007ffff591e2c2 in TTFLangNamesFree (l=0x886840) at splineutil.c:5642
#6  0x00007ffff5921277 in SplineFontFree (sf=0x884840) at splineutil.c:6485
#7  0x00007ffff793e0c2 in FontView_Free (fv=0x15fcd10) at fontview.c:7550
#8  0x00007ffff793caca in FontViewRemove (fv=0x15fcd10) at fontview.c:7156
#9  0x00007ffff793cdfa in fv_e_h (gw=0x19fd050, event=0x7fffffffba40)
    at fontview.c:7237
#10 0x00007ffff681ebfc in _GWidget_Container_eh (gw=0x19fd050, 
    event=0x7fffffffba40) at gcontainer.c:403
#11 0x00007ffff6820189 in _GWidget_TopLevel_eh (gw=0x19fd050, 
    event=0x7fffffffba40) at gcontainer.c:745
#12 0x00007ffff689e70c in dispatchEvent (gdisp=0x69dcf0, event=0x7fffffffbbf0)
    at gxdraw.c:3478
---Type <return> to continue, or q <return> to quit---
#13 0x00007ffff689eca2 in GXDrawEventLoop (gd=0x69dcf0) at gxdraw.c:3586
#14 0x00007ffff6823708 in GDrawEventLoop (gdisp=0x69dcf0) at gdraw.c:791
#15 0x00007ffff7a549a1 in fontforge_main (argc=1, argv=0x7fffffffdf18)
    at startui.c:1382
#16 0x00000000004007e6 in main (argc=1, argv=0x7fffffffdf18) at main.c:39
(gdb) up
#1  0x00007ffff71d4528 in __GI_abort () at abort.c:89
89	abort.c: Aucun fichier ou dossier de ce type.
(gdb) up
#2  0x00007ffff7213f74 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff731cf00 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
175	../sysdeps/posix/libc_fatal.c: Aucun fichier ou dossier de ce type.
(gdb) up
#3  0x00007ffff721b586 in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff731d0c8 "double free or corruption (fasttop)", action=1)
    at malloc.c:4996
4996	malloc.c: Aucun fichier ou dossier de ce type.
(gdb) up
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0)
    at malloc.c:3840
3840	in malloc.c
(gdb) up
#5  0x00007ffff591e2c2 in TTFLangNamesFree (l=0x886840) at splineutil.c:5642
5642		    free(l->names[i]);
(gdb) p l->names[i]
$1 = 0x8867c0 "\240\066\034\001"
(gdb) p i
$2 = 0
(gdb) p l->names
$3 = {0x8867c0 "\240\066\034\001", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
  0x890f40 "Source is a trademark of Adobe Systems Incorporated in the United States and/or other countries.", 0x0, 0x0, 0x0, 0x0, 0x0, 
  0x891140 "This Font Software is licensed under the SIL Open Font License, Version 1.1.\nThis license is available with a FAQ at: http://scripts.sil.org/OFL. This Font Software is distributed on an 'AS IS' BASIS,"..., 
  0x888bf0 "http://scripts.sil.org/OFL", 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
  0x0}
(gdb) 
~~~

See the last $3 struct of strings, the first member contains junk data that has overwritten the original metadata and is not malloc'ed causing invalid free.

cc @frank-trampe

**Comment by frank-trampe** [comment]
Just to confirm, this is reproducible?

**Comment by adrientetar** [comment]
Yes

**Comment by jtanx** [comment]
I've tested both with and without #2214. It does appear to fix the issue - after patching, no double free error appears. Valgrind also doesn't show anything after patching.
