### ISSUE TITLE
Crash when change weight of DroidSansFallbackFull.ttf

### ISSUE THREAD

**Issue by chloerei** [fontforge/fontforge#2414]
Ubuntu 14.04
FontForge 20150612 install from PPA

Font: DroidSansFallbackFull.ttf [download](http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/trusty/fonts-android/trusty/download/package-import%40ubuntu.com-20121128221606-2ymqz74umpj2823t/droidsansfallbackful-20121209165530-2fouva0w10m2w72c-25/DroidSansFallbackFull.ttf)

Select All -> Chagne Weight -> set 13 em units -> Ok -> Crash after ten seconds

Backtrace:

```
...
Internal Error (overlap): The start of the monotonic does not match that of the containing spline.
Internal Error (overlap): The start of the monotonic does not match that of the containing spline.
Internal Error (overlap): The start of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
Internal Error (overlap): The start of the monotonic does not match that of the containing spline.
Internal Error (overlap): The end of the monotonic does not match that of the containing spline.
*** Error in `/usr/bin/fontforge': double free or corruption (fasttop): 0x00000000038134a0 ***

Program received signal SIGABRT, Aborted.
0x00007ffff7314cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7314cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff73180d8 in __GI_abort () at abort.c:89
#2  0x00007ffff7351394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff745fb28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff735d66e in malloc_printerr (ptr=<optimized out>, str=0x7ffff745fcf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007ffff5b0288a in ?? () from /usr/lib/libfontforge.so.2
#6  0x00007ffff5b048b5 in ?? () from /usr/lib/libfontforge.so.2
#7  0x00007ffff5b06fd0 in SplineSetStroke () from /usr/lib/libfontforge.so.2
#8  0x00007ffff5a82ccd in ?? () from /usr/lib/libfontforge.so.2
#9  0x00007ffff5a9678d in ?? () from /usr/lib/libfontforge.so.2
#10 0x00007ffff5a96c35 in FVEmbolden () from /usr/lib/libfontforge.so.2
#11 0x00007ffff7a520e6 in ?? () from /usr/lib/libfontforgeexe.so.2
#12 0x00007ffff69aa318 in ?? () from /usr/lib/libgdraw.so.5
#13 0x00007ffff69aa773 in ?? () from /usr/lib/libgdraw.so.5
#14 0x00007ffff69b268f in ?? () from /usr/lib/libgdraw.so.5
#15 0x00007ffff69b2b63 in ?? () from /usr/lib/libgdraw.so.5
#16 0x00007ffff69fa873 in ?? () from /usr/lib/libgdraw.so.5
#17 0x00007ffff69fbee3 in ?? () from /usr/lib/libgdraw.so.5
#18 0x00007ffff7a5962f in EmboldenDlg () from /usr/lib/libfontforgeexe.so.2
#19 0x00007ffff69d254e in ?? () from /usr/lib/libgdraw.so.5
#20 0x00007ffff69d26fb in ?? () from /usr/lib/libgdraw.so.5
#21 0x00007ffff69fa873 in ?? () from /usr/lib/libgdraw.so.5
#22 0x00007ffff69fcbe2 in ?? () from /usr/lib/libgdraw.so.5
#23 0x00007ffff7a71ad0 in fontforge_main () from /usr/lib/libfontforgeexe.so.2
#24 0x00007ffff72ffec5 in __libc_start_main (main=0x4006d0 <main>, argc=1, argv=0x7fffffffddb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
```

**Comment by jtanx** [comment]
~~~~~
#0  0x00007ffff71edcc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff71f10d8 in __GI_abort () at abort.c:89
#2  0x00007ffff722a394 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff7338b28 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff723666e in malloc_printerr (ptr=<optimised out>, 
    str=0x7ffff7338cf0 "double free or corruption (fasttop)", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimised out>, p=<optimised out>, have_lock=0)
    at malloc.c:3840
#5  0x00007ffff594f982 in SplinePointFree (sp=0x392c5c0) at splineutil.c:168
#6  0x00007ffff5930d62 in RemoveBackForthLine (ss=0x30e89bf0)
    at splinestroke.c:3170
#7  0x00007ffff5930e76 in SSRemoveBackForthLine (contours=0x30e89bf0)
    at splinestroke.c:3205
#8  0x00007ffff5933184 in ApproximateStrokeContours (c=0x7fffffff9ad0)
    at splinestroke.c:3570
#9  0x00007ffff593333c in SplineSet_Stroke (ss=0x392a400, c=0x7fffffff9ad0, 
    order2=1) at splinestroke.c:3607
#10 0x00007ffff59333dd in SplineSets_Stroke (ss=0x392a400, c=0x7fffffff9ad0, 
    order2=1) at splinestroke.c:3622
#11 0x00007ffff59338ec in SplineSetStroke (ss=0x392a400, si=0x7fffffff9ca0, 
    order2=1) at splinestroke.c:3689
#12 0x00007ffff585e339 in BoldSSStroke (ss=0x392a400, si=0x7fffffff9ca0, 
    order2=1, ro=1) at scstyles.c:83
#13 0x00007ffff5875247 in SCEmbolden (sc=0x392a100, zones=0x7fffffff9db0, 
    layer=1) at scstyles.c:4051
#14 0x00007ffff58764d3 in FVEmbolden (fv=0x92ce70, type=embolden_auto, 
    zones=0x7fffffff9db0) at scstyles.c:4311
#15 0x00007ffff7a23a6b in Embolden_OK (g=0x28c83d60, e=0x7fffffff9f60)
    at scstylesui.c:1868
#16 0x00007ffff683e9dd in _GWidget_TopLevel_Key (top=0x28c80010, 
    ew=0x28c80010, event=0x7fffffffa0f0) at gcontainer.c:552
#17 0x00007ffff683f0f1 in _GWidget_TopLevel_eh (gw=0x28c80010, 
...
~~~~~

**Comment by ctrlcctrlv** [comment]
The problem glyph is 33287 U+8207 與.

Here is a minimal font that shows the problem quickly:

```
SplineFontDB: 3.0
FontName: Untitled1
FullName: Untitled1
FamilyName: Untitled1
Weight: Regular
Copyright: Copyright (c) 2015, fredrick
UComments: "2015-7-10: Created with FontForge (http://fontforge.org)"
Version: 001.000
ItalicAngle: 0
UnderlinePosition: -100
UnderlineWidth: 50
Ascent: 800
Descent: 200
InvalidEm: 0
LayerCount: 2
Layer: 0 0 "Back" 1
Layer: 1 0 "Fore" 0
XUID: [1021 885 -1366194050 3828598]
OS2Version: 0
OS2_WeightWidthSlopeOnly: 0
OS2_UseTypoMetrics: 1
CreationTime: 1436510648
ModificationTime: 1436510664
OS2TypoAscent: 0
OS2TypoAOffset: 1
OS2TypoDescent: 0
OS2TypoDOffset: 1
OS2TypoLinegap: 0
OS2WinAscent: 0
OS2WinAOffset: 1
OS2WinDescent: 0
OS2WinDOffset: 1
HheadAscent: 0
HheadAOffset: 1
HheadDescent: 0
HheadDOffset: 1
OS2Vendor: 'PfEd'
DEI: 91125
Encoding: ISO8859-1
UnicodeInterp: none
NameList: AGL For New Fonts
DisplaySize: -72
AntiAlias: 1
FitToEm: 0
WinInfo: 48 8 2
BeginChars: 256 1

StartChar: zero
Encoding: 48 48 0
Width: 256
VWidth: 256
Flags: HWO
LayerCount: 2
Fore
SplineSet
72 205 m 1
 86 190 l 1
 74.6666666667 183.333333333 62 178.333333333 48 175 c 1
 48 148 l 1
 81 148 l 1
 81 131 l 1
 48 131 l 1
 48 100 l 1
 81 100 l 1
 81 83 l 1
 48 83 l 1
 48 53 l 1
 96 53 l 1
 96 111 l 1
 114 111 l 1
 114 53 l 1
 138 53 l 1
 138 124 l 1
 96 124 l 1
 96 207 l 1
 114 207 l 1
 114 185 l 1
 162 185 l 1
 162 168 l 1
 114 168 l 1
 114 140 l 1
 157 140 l 1
 157 53 l 1
 209 53 l 1
 209 83 l 1
 172 83 l 1
 172 100 l 1
 209 100 l 1
 209 131 l 1
 172 131 l 1
 172 148 l 1
 209 148 l 1
 209 182 l 1
 173 182 l 1
 173 200 l 1
 228 200 l 1
 228 53 l 1
 242 53 l 1
 242 35 l 1
 13 35 l 1
 13 53 l 1
 29 53 l 1
 29 188 l 1
 45.6666666667 192 60 197.666666667 72 205 c 1
86 29 m 1
 102 16 l 1
 81.3333333333 0 56.6666666667 -13.3333333333 28 -24 c 1
 14 -5 l 1
 40.6666666667 3 64.6666666667 14.3333333333 86 29 c 1
158 29 m 1
 186.666666667 20.3333333333 213.333333333 9.66666666667 238 -3 c 1
 229 -23 l 1
 202.333333333 -8.33333333333 175.666666667 3.33333333333 149 12 c 1
 158 29 l 1
EndSplineSet
EndChar
EndChars
EndSplineFont
```

Select the 0, Element->Change Weight, 13 em units, boom!

It must be 13 em units, nothing else crashes. 12 and 14 are fine.

**Comment by ctrlcctrlv** [comment]
I have found the exact problem. 

FontForge is getting confused with this stroke in particular:

![clear4](https://cloud.githubusercontent.com/assets/838783/8613618/9caf40b6-2713-11e5-8e7f-062f5cabe200.png)

If I move it down a bit no crash.

![clear4](https://cloud.githubusercontent.com/assets/838783/8613631/b8549d7a-2713-11e5-8ccb-cf4ed1eb318d.png)
![clear5](https://cloud.githubusercontent.com/assets/838783/8613641/caf41cd0-2713-11e5-9d4c-d46d5a70cda8.png)

I think it is making improper assumptions in the merging.

**Comment by ctrlcctrlv** [comment]
Hehehe.

![hehe](https://cloud.githubusercontent.com/assets/838783/8613727/b05e1c9e-2714-11e5-895f-e41502745381.png)

I know what it is doing but I don't understand FF's code well enough to fix it. Very amusing bug. I am trying to fix it anyway, I believe the problem is here:

https://github.com/fontforge/fontforge/blob/master/fontforge/splinestroke.c#L3170

I think it is trying to call free twice on the same point because they have same coords. Thus exactly as error says, *double free*.

**Comment by jtanx** [comment]
It might be worth chucking it through Valgrind to see where the double free is ocurring

**Comment by jtanx** [comment]
~~~~~
==11536== Invalid read of size 8
==11536==    at 0x721FABC: RemoveBackForthLine (splinestroke.c:3166)
==11536==    by 0x721FC2B: SSRemoveBackForthLine (splinestroke.c:3205)
==11536==    by 0x7221F39: ApproximateStrokeContours (splinestroke.c:3570)
==11536==    by 0x72220F1: SplineSet_Stroke (splinestroke.c:3607)
==11536==    by 0x7222192: SplineSets_Stroke (splinestroke.c:3622)
==11536==    by 0x7222638: SplineSetStroke (splinestroke.c:3685)
==11536==    by 0x714D235: BoldSSStroke (scstyles.c:83)
==11536==    by 0x7164387: SCEmbolden (scstyles.c:4065)
==11536==    by 0x716539B: CVEmbolden (scstyles.c:4313)
==11536==    by 0x50C0A48: Embolden_OK (scstylesui.c:1870)
==11536==    by 0x61279A6: GButtonInvoked (gbuttons.c:255)
==11536==    by 0x6128881: gbutton_mouse (gbuttons.c:483)
==11536==  Address 0xe679d10 is 64 bytes inside a block of size 96 free'd
==11536==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11536==    by 0x723E637: SplinePointFree (splineutil.c:168)
==11536==    by 0x721FAB3: RemoveBackForthLine (splinestroke.c:3165)
==11536==    by 0x721FC2B: SSRemoveBackForthLine (splinestroke.c:3205)
==11536==    by 0x7221F39: ApproximateStrokeContours (splinestroke.c:3570)
==11536==    by 0x72220F1: SplineSet_Stroke (splinestroke.c:3607)
==11536==    by 0x7222192: SplineSets_Stroke (splinestroke.c:3622)
==11536==    by 0x7222638: SplineSetStroke (splinestroke.c:3685)
==11536==    by 0x714D235: BoldSSStroke (scstyles.c:83)
==11536==    by 0x7164387: SCEmbolden (scstyles.c:4065)
==11536==    by 0x716539B: CVEmbolden (scstyles.c:4313)
==11536==    by 0x50C0A48: Embolden_OK (scstylesui.c:1870)
==11536== 
~~~~~
