### ISSUE TITLE
fontforge.exe has stopped working

### ISSUE THREAD

**Issue by thsobota** [fontforge/fontforge#2472]
8/30/2015

When I start fontforge, a window pops up that says "fontforge.exe has stopped working"  "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

I am running on a 64 bit  Windows 7 computer with administrator privileges.  I tried this on a desktop that is part of a windows domain and on a laptop that is not part of a domain.  I get the same result both times.  Also, when I install, I get a Windows security request for some element of the program to be able to go through the firewall. I allowed it.

**Comment by thsobota** [comment]
The windw that pops up asks to unblock vcxsrv.

**Comment by thsobota** [comment]
Is it possible that this is a problem with the Font that I am opening?  I tried opening a similar Font and it has not crashed yet.

**Comment by jtanx** [comment]
Quite possibly yes - is it possible for you to upload the font that is causing FontForge to crash? Thanks!

**Comment by thsobota** [comment]
I don't know how to upload but the font can be found at http://www.dafont.com/highway-gothic.font

It is the font HWYGOTH.TTF.  This one causes the crash.  If I open some of the other fonts in this upload, it does not crash.

**Comment by jtanx** [comment]
Thanks for the link - I can reproduce the crash:

~~~~~
Program received signal SIGSEGV, Segmentation fault.
0x7510a3f1 in wcstok_s () from C:\WINDOWS\SYSTEM32\msvcrt.dll
(gdb) bt
#0  0x7510a3f1 in wcstok_s () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#1  0x7510a328 in wcstok_s () from C:\WINDOWS\SYSTEM32\msvcrt.dll
#2  0x6e870371 in BdfCFromBitmap (bitmap=0x29e3bc, bitmap_left=3276,
    bitmap_top=43909, pixelsize=65535, depth=4, sc=0x2deb260, metrics=0x0)
    at freetype.c:398
#3  0x6e872e8b in SplineCharFreeTypeRasterizeNoHints (sc=0x2deb260, layer=1,
    ptsize=65535, dpi=72, depth=4) at freetype.c:1092
#4  0x6e9e2424 in BDFPieceMeal (bdf=0x2fab580, index=23) at splinefill.c:1690
#5  0x636c1d6c in FVDrawGlyph (pixmap=0x2c51098, fv=0x2c41c90, index=53,
    forcebg=0) at fontview.c:243
#6  0x636d39ba in FVExpose (fv=0x2c41c90, pixmap=0x2c51098, event=0x29f180)
    at fontview.c:6310
#7  0x636d6438 in v_e_h (gw=0x2c51098, event=0x29f180) at fontview.c:7029
#8  0x6ef9445b in _GWidget_Container_eh (gw=0x2fa8300, event=0x29f180)
    at gcontainer.c:279
#9  0x6eff616c in GXDrawRequestExpose (gw=0x2fa8300, rect=0x29f1c8, doclear=1)
    at gxdraw.c:2485
#10 0x6ef98625 in GDrawRequestExpose (w=0x2fa8300, rect=0x0, doclear=1)
    at gdraw.c:745
#11 0x636d5f67 in FVResize (fv=0x2c41c90, event=0x2c41cec) at fontview.c:6929
#12 0x636d61de in FVTimer (fv=0x2c41c90, event=0x29f3f0) at fontview.c:6964
#13 0x636d6510 in v_e_h (gw=0x2fa8300, event=0x29f3f0) at fontview.c:7045
#14 0x6ef94c1c in _GWidget_Container_eh (gw=0x2fa8300, event=0x29f3f0)
    at gcontainer.c:403
#15 0x6eff673b in GXDrawProcessTimerEvent (gdisp=0x24cf828, timer=0x2c3a820)
    at gxdraw.c:2657
#16 0x6eff6801 in GXDrawCheckPendingTimers (gdisp=0x24cf828) at gxdraw.c:2684
#17 0x6eff690e in GXDrawWaitForEvent (gdisp=0x24cf828) at gxdraw.c:2722
#18 0x6eff83c0 in GXDrawEventLoop (gd=0x24cf828) at gxdraw.c:3403
#19 0x6ef9879a in GDrawEventLoop (gdisp=0x24cf828) at gdraw.c:791
#20 0x637983c5 in fontforge_main (argc=1, argv=0xd47e90) at startui.c:1373
#21 0x00401650 in main (argc=1, argv=0xd47e90) at main.c:39

~~~~~

**Comment by jtanx** [comment]
The issue is that the FreeType bitmap is larger (29754x44696) than can be held in signed 16-bit integers (32767) (BDFChar), which causes the BDF height(ymin/ymax) to overflow/become negative. This causes the malloc call to fail and return NULL, hence the subsequent call to memcpy segfaulting.

I don't know the proper solution to this. @mskala...?

**Comment by mskala** [comment]
It might be possible to change that data structure to use wider integers.  I think it probably used a 16-bit limit only because of some limitation in the BDF format, and since it's really an in-memory data structure used for bitmaps in general (not only BDFs), it should be okay to make it larger as long as there's no need to actually write such huge bitmaps into a file format that can't handle them.

But *why* is such an insanely huge bitmap being generated at all?  That seems like it can't possibly be a good thing to do.
