### ISSUE TITLE
MacOS app not working

### ISSUE THREAD

**Issue by hejsan** [fontforge/fontforge#2481]
As suggested on your dowload page it quits immediately. I couldn't find the issue for that so I made this one to report :-\
Launching it from the commandline also doesn't work:
```
applebloom:~ b$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
applebloom:~ b$ dyld: Library not loaded: /opt/local/lib/libgdraw.5.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
serving at port 8000
applebloom:~ b$
```
It looks like it's referring to some libraries from system root (/opt/...)instead of its own directory (Applications/FontForge.app/Contents/Resources/opt/)

**Comment by cridenour** [comment]
Yea I had a real rough time with this. I edited the executable to add in the correct library path, with correct fallbacks - but after install libjpeg.9, libspiro, and libuninameslist, it complained my version of libxml2.2 was out of date - at which point I gave up.

The changes I made to /Applications/FontForge.app/Contents/MacOS/FontForge at line 50:

```bash
export DYLD_LIBRARY_PATH="$bundle_lib"
export DYLD_FALLBACK_LIBRARY_PATH="/opt/local/lib:/usr/local/lib:/opt/X11/lib:/usr/lib"
```

Maybe someone else can have better luck!

**Comment by jaanush** [comment]
I'm having the same issue - gave up after the homebrew version of libjpeg9 vas 10.0 not 11.0 as FF required.

**Comment by bsalinas** [comment]
For others having this problem, I was able to successfully install the version from April 30 (https://github.com/fontforge/fontforge/releases/tag/20150430).

**Comment by worldofhurtado** [comment]
@bsalinas I ended up doing the same thing and forgot to come back here and update people. thanks!

**Comment by ultrasquid** [comment]
I'm using OSX 10.6.8 and I am able to run @monkeyiq 's build from
http://fuuko.libferris.com/osx/packages/201509/17_0419/ ,
It was posted just a week ago, but I can't tell how recent the source is
that it was built from.

On Thu, Sep 24, 2015 at 8:55 AM, worldofhurtado <notifications@github.com>
wrote:

> @bsalinas <https://github.com/bsalinas> I ended up doing the same thing
> and forgot to come back here and update people. thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2481#issuecomment-142971642>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by dupush** [comment]
Thanks @bsalinas for your solution. It works for me too on OSX 10.10.5.

**Comment by nifl** [comment]
Fontforge-20150824 wouldn't launch for me on Mac OS 10.11. I reverted to FontForge-2015-04-30-Mac.app per @bsalinas suggestion and that one launches in my environment.

**Comment by atomicframeworks** [comment]
Also had issues loading FontForge 2015-08-24 while running Mac OS 10.10.5.  @bsalinas suggested build wouldn't load either, but @monkeyiq 's build seems to work alright.

**Comment by jtanx** [comment]
#2530
