### ISSUE TITLE
New Mac Build?

### ISSUE THREAD

**Issue by arandorion** [fontforge/fontforge#2513]
Any idea when there will be a new Mac build that runs on OS X 10.10.5?

Thanks

**Comment by adamschwartz** [comment]
:+1:

**Comment by davelab6** [comment]
I confirm that the August release does not run on 10.10.5. 

https://github.com/fontforge/fontforge/releases/tag/20150824

```sh
$ open /Applications/FontForge.app;
$ /Applications/FontForge.app/Contents/MacOS/FontForge 
PKGBASE: /Applications/FontForge.app
dyld: Library not loaded: /opt/local/lib/libgdraw.5.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 200, in <module>
    httpd = SocketServer.TCPServer(("127.0.0.1", PORT), Handler)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use
$
```

**Comment by arandorion** [comment]
They already fixed it, they just haven't released a new build.
