### ISSUE TITLE
Fontforge crashes on iMac retina 5k on OSX 10.10.5

### ISSUE THREAD

**Issue by fwlab** [fontforge/fontforge#2535]
Launching via terminal produces the following output. NB: XCrystal is installed and updated to latest version.

iMac-di-Michele-n2:~ michelefadda$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
iMac-di-Michele-n2:~ michelefadda$ dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
serving at port 8000

**Comment by typoman** [comment]
I got similar error on 10.9.5, retina macbook:
```
~$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
~$ ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
serving at port 8000
```

**Comment by lholsti** [comment]
Same error here, late 2010 macbook pro, os x 10.9.5, xquartz 2.7.8

dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
serving at port 8000

**Comment by jtanx** [comment]
#2530
