### ISSUE TITLE
Fontforge 20150824 doesn't start on OS X 10.11

### ISSUE THREAD

**Issue by sfcgeorge** [fontforge/fontforge#2542]
Clicking the icon does nothing. Running from the terminal with the suggested command: 

```
/Applications/FontForge.app/Contents/MacOS/FontForge
```

Produced this error: 

```
PKGBASE: /Applications/FontForge.app
dyld: Library not loaded: /opt/local/lib/libgdraw.5.dylib                                           
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SimpleHTTPServer.py", line 15, in <module>
    import BaseHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/BaseHTTPServer.py", line 81, in <module>
    import mimetools
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/random.py", line 48, in <module>
    from binascii import hexlify as _hexlify
ImportError: dlopen(/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so, 2): Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so
  Reason: image not found
```

**Comment by sfcgeorge** [comment]
The version in this thread does work though: https://github.com/fontforge/fontforge/issues/2530#issuecomment-148997584

**Comment by zeyangl** [comment]
Upvote. Same problem.

**Comment by jBot-42** [comment]
Same for me.

**Comment by michaelappuhn** [comment]
@sfcgeorge @zeyangl The version in #2530 will open for me, but will freeze when attempting to save files. Do either of you have this problem? Since this is such a specific workaround, I don't think this deserves a new thread.

**Comment by my-flow** [comment]
@michaelappuhn Same problem here. The head version in [#2530 (comment)](https://github.com/fontforge/fontforge/issues/2530#issuecomment-148997584) worked for me. No problems when saving files.
