### ISSUE TITLE
Trying to run on OSX, fails with "Reason: image not found"

### ISSUE THREAD

**Issue by BoD** [fontforge/fontforge#2605]
I just tried to run this version:
`https://github.com/fontforge/fontforge/releases/download/20150824/Fontforge-2015-08-24-Terminal_only.dmg`

And here's the results:

```
$ /Applications/FontForge.app/Contents/MacOS/FontForge
PKGBASE: /Applications/FontForge.app
dyld: Library not loaded: /opt/local/lib/libfontforgeexe.2.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge
  Reason: image not found
$ Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SimpleHTTPServer.py", line 15, in <module>
    import BaseHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/BaseHTTPServer.py", line 81, in <module>
    import mimetools
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/random.py", line 48, in <module>
    from binascii import hexlify as _hexlify
ImportError: dlopen(/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so, 2): Library not loaded: /opt/local/lib/libz.1.dylib
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/binascii.so
  Reason: image not found
```

My OSX version:

```
10.11.2 (15C50)

$ uname -a
Darwin BoDs-MacBook-Pro.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```

**Comment by marnen** [comment]
I've had the same problem (on El Capitan). I wonder if that build is broken. Try the 30 April release instead.

**Comment by vjandrea** [comment]
Same error here:
````
$ sw_vers -productVersion 
10.11.3

$ uname -a
Darwin MacBook-Pro.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
````
