### ISSUE TITLE
Crash when glyph window is closed while problem is displayed (with stacktrace)

### ISSUE THREAD

**Issue by gioele** [fontforge/fontforge#2814]
Fontforge will crash if a glyph window is closed while a dialog box with a problem is displayed.

Steps to reproduce under Ubuntu 12.04 with Fontforge 20160405 from the PPA:

* open a font in Fontforge;
* double click on a glyph that has at least one error;
* from the menu bar of the glyph window select "Element" → "Find problems...";
* click on "Set all" then "OK";
* wait for a problem to be reported in a new dialog box;
* close the glyph window (clicking on the "X" button in the window decoration);
* close the problem window
* CRASH

Here is the backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7992cf2 in CVClearSel (cv=0xddd470) at cvpointer.c:186
186	cvpointer.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7992cf2 in CVClearSel (cv=0xddd470) at cvpointer.c:186
#1  0x00007ffff7a3a85b in ExplainIt (p=0x7fffffffa8d0, sc=0xb1de10, 
    explain=0x7ffff7ab6e88 "The y coord of the selected point is near the xheight", found=1038, 
    expected=1037) at problems.c:648
#2  0x00007ffff7a3bae0 in SCProblems (cv=0xddd470, sc=0xb1de10, p=0x7fffffffa8d0)
    at problems.c:1267
#3  0x00007ffff7a3fd63 in DoProbs (p=0x7fffffffa8d0) at problems.c:2784
#4  0x00007ffff7a41e98 in Prob_OK (g=<optimized out>, e=<optimized out>) at problems.c:2970
#5  Prob_OK (g=<optimized out>, e=<optimized out>) at problems.c:2863
#6  0x00007ffff69a8c63 in GButtonInvoked (b=0xe7ef60, ev=0x7fffffff63f0) at gbuttons.c:255
#7  0x00007ffff69a9155 in gbutton_mouse (g=0xe7ef60, event=0x7fffffff63f0) at gbuttons.c:483
#8  0x00007ffff69b1440 in _GWidget_Container_eh (gw=0xe67bf0, event=0x7fffffff63f0)
    at gcontainer.c:302
#9  0x00007ffff69b195b in _GWidget_TopLevel_eh (event=0x7fffffff63f0, gw=0xe67bf0)
    at gcontainer.c:745
#10 _GWidget_TopLevel_eh (gw=0xe67bf0, event=0x7fffffff63f0) at gcontainer.c:616
#11 0x00007ffff69fce4d in dispatchEvent (gdisp=<optimized out>, event=0x7fffffff6760)
    at gxdraw.c:3296
#12 0x00007ffff69fe129 in GXDrawProcessOneEvent (gdisp=0x69a9e0) at gxdraw.c:3328
#13 0x00007ffff7a45fff in FindProblems (fv=<optimized out>, cv=<optimized out>, sc=<optimized out>)
    at problems.c:4164
#14 0x00007ffff69d2271 in gmenu_mouse (event=0x7fffffffb800, m=0xe685e0) at gmenu.c:943
#15 gmenu_mouse (m=<optimized out>, event=0x7fffffffb800) at gmenu.c:837
#16 0x00007ffff69d2743 in gmenu_eh (w=0xe4a670, ge=0x7fffffffb800) at gmenu.c:1378
#17 0x00007ffff69fce4d in dispatchEvent (gdisp=<optimized out>, event=0x7fffffffbb70)
    at gxdraw.c:3296
#18 0x00007ffff69fee7e in GXDrawEventLoop (gd=0x69a9e0) at gxdraw.c:3404
#19 0x00007ffff7a73ef5 in fontforge_main (argc=<optimized out>, argv=<optimized out>)
    at startui.c:1378
#20 0x00007ffff73017ed in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#21 0x0000000000400671 in _start ()
```

**Comment by jtanx** [comment]
So just to clarify:
> close the glyph window

Do you mean the glyph editing window (charview) for the problem glyph or the main window (fontview)? I can cause it to crash if I close all the windows except the 'find problems' window, but I can't get it to crash if I simply close the charview before closing the 'find problems' window.

**Comment by frank-trampe** [comment]
I think there's an old issue on this. I looked at fixing it, but there wasn't an easy, elegant solution. I'll try to find it later.

**Comment by frank-trampe** [comment]
It was #1451.
