### ISSUE TITLE
"PS Interpretion" dialog may be causing Python script to hang

### ISSUE THREAD

**Issue by robmadole** [fontforge/fontforge#2832]
FontForge version: 20160404
OS: Ubuntu 14.04.5 LTS

We are using FontForge to import SVGs and have ran across an icon that causes the "PS Interpretion" dialog to appear whenever we use the GUI. It also causes FontForge to crash if I dismiss the dialog.

To reproduce the behavior I create a new font, choose a glyph, and then choose File -> Import. Use the following SVG file:

[bad-icon.svg.zip](https://github.com/fontforge/fontforge/files/473448/bad-icon.svg.zip)

And this appears:

![dialog](https://cloud.githubusercontent.com/assets/132895/18529797/3644ec1a-7a94-11e6-8ae2-209e1ad181cf.png)

Since we are using this in a Python script I suspect that there is no way to dismiss this dialog and the script will hang indefinitely. If I could dismiss the dialog FontForge still crashes which is actually preferable to it hanging.

**Comment by jtanx** [comment]
~~~~~
Program received signal SIGSEGV, Segmentation fault.
0x6ea279be in RemoveBackForthLine (ss=0x43edfa8) at splinestroke.c:3194
3194            sp = sp->next->to;
(gdb) bt
#0  0x6ea279be in RemoveBackForthLine (ss=0x43edfa8) at splinestroke.c:3194
#1  0x6ea27962 in RemoveBackForthLine (ss=0x0) at splinestroke.c:3181
#2  0x6ea27962 in RemoveBackForthLine (ss=0x42a2898) at splinestroke.c:3181
#3  0x6ea27a09 in SSRemoveBackForthLine (contours=0x42b5570) at splinestroke.c:3
212
#4  0x6ea29105 in ApproximateStrokeContours (c=0x60e788) at splinestroke.c:3577
#5  0x6ea29271 in SplineSet_Stroke (ss=0x42414d0, c=0x60e788, order2=0) at splin
estroke.c:3614
#6  0x6ea292fe in SplineSets_Stroke (ss=0x42414d0, c=0x60e788, order2=0) at spli
nestroke.c:3629
#7  0x6ea296d1 in SplineSetStroke (ss=0x42414d0, si=0x60e920, order2=0) at splin
estroke.c:3696
#8  0x6e92d23b in SplinesFromEntityChar (ec=0x60e9c8, flags=0x60ea18, is_stroked
=0) at psread.c:3135
#9  0x6e92d46d in SplinesFromEntities (ent=0x423e990, flags=0x60ea18, is_stroked
=0) at psread.c:3188
...

(gdb) p sp
$2 = (SplinePoint *) 0x4242378
(gdb) p sp->next
$3 = (struct spline *) 0xfeeefeee                      <- free memory!!!
(gdb) p sp->next->to
Cannot access memory at address 0xfeeefef6
~~~~~

**Comment by jtanx** [comment]
There's obviously an issue with the import, but it's not hanging vs crashing in scripting because of the dialogue - it's by chance. I got it to hang in the GUI while running on Linux, probably as it entered an infinite loop doing things it shouldn't with freed memory.

**Comment by jtanx** [comment]
[j.zip](https://github.com/fontforge/fontforge/files/473864/j.zip)

It hangs in the stroker - I've attached part of the svg (part of 'j') that causes it to hang (this is just one part that causes a hang).

**Comment by jtanx** [comment]
Okay... The long and the short of it is that the logo is small (FF doesn't upscale it) and FF really doesn't like the stroked paths that's applied to some of the glyphs - e.g. 'j', which has a stroked path with a width of 0.67px(!!!!). I can make it so it doesn't crash, but the result won't be particularly meaningful.

**Comment by robmadole** [comment]
@jtanx thank you for taking a look at this. For what it's worth if FF crashed that would actually be preferable for us because it would then just cause uWSGI to restart and life would continue. However, that's really not a desirable thing for users of the GUI.

**Comment by skef** [comment]
As of my testing this evening importing this SVG segfaults in the Remove Overlap code:

```
       Message: Process 18381 (fontforge) of user 1000 dumped core.
                
                Stack trace of thread 18381:
                #0  0x00007f351c97750f SSRmNullSplines (libfontforge.so.4)
                #1  0x00007f351c9778f4 SSToMContour (libfontforge.so.4)
                #2  0x00007f351c977af3 SSsToMContours (libfontforge.so.4)
                #3  0x00007f351c98ab37 SplineSetRemoveOverlap (libfontforge.so.4)
                #4  0x00007f351c9b9dbb SplineSetStroke (libfontforge.so.4)
                #5  0x00007f351c8702d7 SplinesFromEntityChar (libfontforge.so.4)
                #6  0x00007f351c870680 SplinesFromEntities (libfontforge.so.4)
                #7  0x00007f351ca27165 SplinePointListInterpretSVG (libfontforge.so.4)
                #8  0x00007f351c7297a9 SCImportSVG (libfontforge.so.4)
                #9  0x0000562f403d99b8 ImportSVG (fontforge)
                #10 0x0000562f403db633 GFD_ImportOk (fontforge)
                #11 0x0000562f405ceaca GFileChooserFListSelected (fontforge)
                #12 0x0000562f405e3639 GListDoubleClick (fontforge)
                #13 0x0000562f405e5a08 glist_mouse (fontforge)
                #14 0x0000562f405c3e22 _GWidget_Container_eh (fontforge)
                #15 0x0000562f405c5ca2 _GWidget_TopLevel_eh (fontforge)
                #16 0x0000562f405d89aa _GGDKDraw_CallEHChecked (fontforge)
                #17 0x0000562f405db3cd _GGDKDraw_DispatchEvent (fontforge)
                #18 0x00007f351b92e694 n/a (libgdk-3.so.0)
                #19 0x00007f351b8db714 n/a (libgdk-3.so.0)
                #20 0x00007f351b3b6cf4 g_main_context_dispatch (libglib-2.0.so.0)
                #21 0x00007f351b3b8b11 n/a (libglib-2.0.so.0)
                #22 0x00007f351b3b8b51 g_main_context_iteration (libglib-2.0.so.0)
                #23 0x0000562f405de0fb GGDKDrawProcessOneEvent (fontforge)
                #24 0x0000562f405c9b22 GDrawProcessOneEvent (fontforge)
                #25 0x0000562f403dcb34 _Import (fontforge)
                #26 0x0000562f403dcb8e CVImport (fontforge)
                #27 0x0000562f4037ecd2 CVMenuImport (fontforge)
                #28 0x0000562f405f710f gmenu_mouse (fontforge)
                #29 0x0000562f405f8bd2 gmenu_eh (fontforge)
                #30 0x0000562f405d89aa _GGDKDraw_CallEHChecked (fontforge)
                #31 0x0000562f405db3cd _GGDKDraw_DispatchEvent (fontforge)
                #32 0x00007f351b92e694 n/a (libgdk-3.so.0)
                #33 0x00007f351b8db714 n/a (libgdk-3.so.0)
                #34 0x00007f351b3b6cf4 g_main_context_dispatch (libglib-2.0.so.0)
                #35 0x00007f351b3b8b11 n/a (libglib-2.0.so.0)
                #36 0x00007f351b3b8b51 g_main_context_iteration (libglib-2.0.so.0)
                #37 0x0000562f405de177 GGDKDrawEventLoop (fontforge)
                #38 0x0000562f405c9bff GDrawEventLoop (fontforge)
                #39 0x0000562f4058dfa0 fontforge_main (fontforge)
                #40 0x0000562f40320b79 main (fontforge)
                #41 0x00007f351b1b1ee3 __libc_start_main (libc.so.6)
                #42 0x0000562f40320a8e _start (fontforge)

```

**Comment by skef** [comment]
Oh: After #4204 is integrated you also won't see the initial symptom listed in this bug: the options dialog can be raised from a script but only when explicitly requested (and the UI is present).
