### ISSUE TITLE
import ssl module error on windows

### ISSUE THREAD

**Issue by zoghal** [fontforge/fontforge#2867]
I'm trying to install pip/setuptools & others modules  to needed, but I'm having trouble with this error 

```
F:\FontForgeBuilds>ffpython -m get-pip.py
F:/FontForgeBuilds/bin/ffpython.exe: No module named get-pip.py

F:\FontForgeBuilds>ffpython get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 19177, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/__init__.py", line 16, in <module>
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/vcs/subversion.py", line 9, in <module>
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/index.py", line 30, in <module>
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/wheel.py", line 39, in <module>
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/_vendor/distlib/scripts.py", line 14, in <module>
  File "c:/users/zoghal/appdata/local/temp/tmpux66ct/pip.zip/pip/_vendor/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
```

after tracing i found a problem, on windows python cannot import _ssl module

```
F:\FontForgeBuilds>ffpython
Python 2.7.11 (default, Mar  4 2016, 09:05:48)  [GCC 5.3.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\FontForgeBuilds\lib\python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified procedure could not be found.
>>> import _ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```

i check this problam by this release:

```
13-08-16:
* Sync with git master (prerelease)
07-04-16:
* Fix crash in kern pairs dialogue (#2681)
* Fix preferences dialogue being too large (#2675)
05-04-16:
* Sync with the April 20160404 release
04-07-15 (14-06-15) (r4):
```

Please guide me how can I solve this problem.
thanks

**Comment by jtanx** [comment]
It looks like I forgot to bundle ssleay32.dll with it. You can extract the dll from here: https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/mingw-w64-i686-openssl-1.0.2.h-1-any.pkg.tar.xz/download

And place it in your bin folder with the rest of the fontforge binaries. I'll make sure to bundle it with the next release.

**Comment by jtanx** [comment]
Although I just tried get pip and I get an exception. Not sure, but it might be related to https://github.com/pypa/pip/issues/2669

**Comment by zoghal** [comment]
I did it, but the problem still remains
