### ISSUE TITLE
python3 - importing psMat fails

### ISSUE THREAD

**Issue by santhoshtr** [fontforge/fontforge#2886]
I compiled latest fontforge(master branch) using PYTHON=python3.  All looks good, import fontforge works. But I have a build script that need psMat.
import psMat fails with the error:

```
Traceback (most recent call last):
  File "tools/build.py", line 11, in <module>
    import psMat
ImportError: 'psMat' is not a built-in module
```

I have the psMat in appropriate place

```
$ ls /usr/local/lib/python3.5/site-packages/
fontforge.la  fontforge.so  psMat.la  psMat.so
```

I found a related qn at http://stackoverflow.com/questions/29441053/importerror-psmat-is-not-a-built-in-module. But that solution of using fontforge's python fails with
```
$ fontforge -script tools/build.py
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 09:55 IST  2-Oct-2016-ML-D.
 Based on source from git with hash: 5b866097a72485d363b8469709b6c4cdbd5e39e1
Traceback (most recent call last):
  File "/usr/local/share/fontforge/python/graphicore.py", line 25, in <module>
    import graphicore.shell
  File "/usr/local/share/fontforge/python/graphicore/shell.py", line 26, in <module>
    import gtk
ImportError: No module named 'gtk'
```
No idea why gtk required for running a script.

**Comment by jtanx** [comment]
I had an inkling I had heard of this issue before and I think I'm right. Please see #1731. I don't think there's a fix as of yet.
