### ISSUE TITLE
Attempting to open a new file causes fontforge to freeze

### ISSUE THREAD

**Issue by michaelappuhn** [fontforge/fontforge#3041]
## Issue
When I attempt to select File > Open, Xquartz freezes completely.  Until I quit Xquartz itself, the application is unresponsive. 

## Context
 - I am running OS X El Capitan, 10.11.
 - I installed FontForge via `homebrew cask`
 - Other menu items, such as (File > Recent) seem to work fine

## Screenshot
Totally unhelpful dropdown screenshot, but why not?

![screen shot 2017-03-03 at 3 26 16 pm](https://cloud.githubusercontent.com/assets/1646731/23567929/7b4e87f4-0026-11e7-9031-4c6d524eb046.png)

## From the Console log
```
3/3/17 3:25:59.661 PM com.apple.xpc.launchd[1]: (org.macosforge.xquartz.privileged_startx[57706]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): org.macosforge.xquartz.privileged_startx
3/3/17 3:25:59.966 PM org.macosforge.xquartz.startx[57697]: expr: syntax error
3/3/17 3:25:59.968 PM org.macosforge.xquartz.startx[57697]: expr: syntax error
3/3/17 3:25:59.970 PM org.macosforge.xquartz.startx[57697]: expr: syntax error
3/3/17 3:25:59.981 PM org.macosforge.xquartz.startx[57697]: xauth:  file /Users/mm/.serverauth.57698 does not exist
3/3/17 3:26:00.014 PM org.macosforge.xquartz.X11.stub[57846]: Xquartz: Unable to locate waiting server: org.macosforge.xquartz.X11
3/3/17 3:26:00.016 PM org.macosforge.xquartz.X11.stub[57847]: Xquartz: Starting X server: /Applications/Utilities/XQuartz.app/Contents/MacOS/X11 --listenonly
3/3/17 3:26:02.017 PM org.macosforge.xquartz.startx[57697]: /opt/X11/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```

**Comment by michaelappuhn** [comment]
## Update
I have tried installing from binaries, several versions, and am going crazy. 

Today I found the following error outputted while launching from the command line. 

```
TESTING: GResourceProgramDir:/Applications/FontForge.app/Contents/Resources/opt/local/bin
trying default theme:/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/resources
Traceback (most recent call last):
  File "/Applications/FontForge.app/Contents/MacOS/fontforge-crash-reporter.py", line 3, in <module>
    import SimpleHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/SimpleHTTPServer.py", line 15, in <module>
    import BaseHTTPServer
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/BaseHTTPServer.py", line 81, in <module>
    import mimetools
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Applications/FontForge.app/Contents/Resources/opt/local/bin/Python.framework.2.7/lib/python2.7/lib-dynload/_io.so
fontforge.hasUserInterface!
PyFF_onAppClosing() cnt:1
SplineFontPieceMeal() going unhinted...
SplineFontPieceMeal() going unhinted...
```

It seems rather arbitrary, but I'm wondering if this has to do with my version of python being installed via homebrew. I've seen this issue pop up for [other](https://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder) [projects](https://github.com/snare/voltron/issues/111), but their fixes don't seem to work.

Anyone have any insight?

**Comment by michaelappuhn** [comment]
This wound up being a fairly simple fix after a lot of google searches. 

The error was coming from the fact that I had homebrew's copy of python 2.7.11, but had neglected to remove old symlinks which were somehow messing with my install. Maybe.

This seems to have worked, though I couldn't explain it if you asked me to:

```
brew unlink python && brew reinstall python
```
