### ISSUE TITLE
save opentypeTTF/OTF's legacy-kern is corrupt when 'too many pairs'

### ISSUE THREAD

**Issue by daT4v1s** [fontforge/fontforge#3509]
- [x] Screenshot 
![screenshot from 2019-02-10 17-26-53](https://user-images.githubusercontent.com/47403824/54022017-87598400-415f-11e9-89b9-be7568feb92e.png)

![screenshot from 2019-02-10 17-55-49 error](https://user-images.githubusercontent.com/47403824/54022033-92141900-415f-11e9-861a-8f2ca41c20dc.png)

![screenshot from 2019-03-07 00-23-13](https://user-images.githubusercontent.com/47403824/54022076-ab1cca00-415f-11e9-8135-67b2cefa1176.png)

- [x] The FontForge version and the operating system you're using
ubuntu build 2019-02feb-15

- [x] The behavior you expect to see, and the actual behavior
when decompiling the outputted font on ttx, i get 

```
ERROR: An exception occurred during the decompilation of the 'kern' table
Traceback (most recent call last):
  File "…/afdko_venv/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 373, in __getitem__
    return self.tables[tag]
KeyError: 'kern'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/afdko_venv/lib/python3.6/site-packages/fontTools/ttLib/ttFont.py", line 392, in __getitem__
    table.decompile(data, self)
  File "…/afdko_venv/lib/python3.6/site-packages/fontTools/ttLib/tables/_k_e_r_n.py", line 68, in decompile
    subtable.decompile(data[:length], ttFont)
  File "…/afdko_venv/lib/python3.6/site-packages/fontTools/ttLib/tables/_k_e_r_n.py", line 149, in decompile
[Example RobotoCondensed-Regular inputfile .otf.zip](https://github.com/fontforge/fontforge/files/2947319/Example.RobotoCondensed-Regular.inputfile.otf.zip)

    left, right, value = next(it), next(it), next(it)

```

although fontforge does not say which `16-bit-field` was truncated (unoptimal),
evidently the legacy kern table was corrupted

to reproduce: 
file>generate  truetype or opentype(cff)
![screenshot from 2019-03-08 15-20-02 output settings](https://user-images.githubusercontent.com/47403824/54053934-da125a80-41b6-11e9-89a0-90a07171cb65.png)

it might be better to fail gracefully 

- to limit number kern pairs of kern-table (easy?)
- prioritize larger-magnitude (positive OR negative) kern offsets and more common characters/symbols

**Comment by ctrlcctrlv** [comment]
> prioritize larger-magnitude (positive OR negative) kern offsets and more common characters/symbols

This is a great idea :+1: 

A Python script could perhaps do it right now if you're in a hurry.

**Comment by daT4v1s** [comment]
also, a fast/simple method would be to 
sort and add all non-zero kern-pairs in order

- that are both keyboard-type-able
- then those that include a keyboard type-able character
- and lastly those where both characters aren't

and then truncating at the limit

**Comment by ValZapod** [comment]
Is there any way to "decompile" a font and look it and saved eith fontforge version? I mean I know even DSIG can be manipulated with ttx command?
