### ISSUE TITLE
*** BUG *** In pixman_region32_init_rect: Invalid rectangle passed

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3579]
Arch Linux, d9726ddef9eb2937f1c145d62b559ceae076ce77

```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

I receive this message in `stdout`, this is not a crash.

Reproduction steps:

1. Open [PixmanBug.zip](https://github.com/fontforge/fontforge/files/3000134/PixmanBug.zip)
1. Press "Y" on the keyboard or select the Y glyph.
1. Press "Ctrl+K" on the keyboard or open the metrics view.

If am unfortunately unable to set a breakpoint at `_pixman_log_error` as suggested. After struggling with this for a bit, I realized that there is *no function by that name* in the program, even if I tell it to "wait for a shared library load"!

```
(gdb) info functions pixman
All functions matching regular expression "pixman":

Non-debugging symbols:
0x00001555538d7070  pixman_image_composite32@plt
0x00001555538d70a0  pixman_region32_equal@plt
0x00001555538d70e0  pixman_glyph_cache_lookup@plt
0x00001555538d7170  pixman_glyph_cache_insert@plt
0x00001555538d71a0  pixman_region32_rectangles@plt
0x00001555538d7200  pixman_composite_glyphs@plt
0x00001555538d7220  pixman_region32_contains_point@plt
0x00001555538d7280  pixman_image_create_bits@plt
0x00001555538d7310  pixman_glyph_cache_remove@plt
0x00001555538d7340  pixman_fill@plt
0x00001555538d73a0  pixman_glyph_get_mask_format@plt
0x00001555538d7430  pixman_add_triangles@plt
0x00001555538d7440  pixman_image_get_format@plt
0x00001555538d7480  pixman_image_get_stride@plt
0x00001555538d75a0  pixman_composite_glyphs_no_mask@plt
0x00001555538d7660  pixman_region32_intersect@plt
0x00001555538d7680  pixman_image_set_destroy_function@plt
0x00001555538d76e0  pixman_region32_init_rects@plt
0x00001555538d76f0  pixman_glyph_cache_destroy@plt
0x00001555538d77f0  pixman_image_get_data@plt
0x00001555538d7920  pixman_region32_contains_rectangle@plt
0x00001555538d7970  pixman_region32_init@plt
0x00001555538d7a70  pixman_image_set_filter@plt
0x00001555538d7aa0  pixman_image_set_repeat@plt
0x00001555538d7ad0  pixman_region32_copy@plt
0x00001555538d7ae0  pixman_image_get_height@plt
0x00001555538d7b60  pixman_region32_not_empty@plt
--Type <RET> for more, q to quit, c to continue without paging--c
0x00001555538d7c90  pixman_image_get_depth@plt
0x00001555538d7d50  pixman_image_ref@plt
0x00001555538d7df0  pixman_image_unref@plt
0x00001555538d7ea0  pixman_glyph_cache_thaw@plt
0x00001555538d7eb0  pixman_rasterize_trapezoid@plt
0x00001555538d7ed0  pixman_image_set_component_alpha@plt
0x00001555538d7f30  pixman_region32_n_rects@plt
0x00001555538d7fc0  pixman_region32_extents@plt
0x00001555538d7fe0  pixman_image_set_transform@plt
0x00001555538d81e0  pixman_format_supported_destination@plt
0x00001555538d8200  pixman_image_set_clip_region32@plt
0x00001555538d8240  pixman_image_create_radial_gradient@plt
0x00001555538d8280  pixman_blt@plt
0x00001555538d8290  pixman_glyph_cache_freeze@plt
0x00001555538d82a0  pixman_image_create_solid_fill@plt
0x00001555538d8370  pixman_region32_subtract@plt
0x00001555538d8530  pixman_image_get_width@plt
0x00001555538d8580  pixman_region32_fini@plt
0x00001555538d85a0  pixman_region32_union@plt
0x00001555538d8760  pixman_transform_point_3d@plt
0x00001555538d87a0  pixman_image_create_linear_gradient@plt
0x00001555538d87d0  pixman_region32_translate@plt
0x00001555538d8880  pixman_region32_init_rect@plt
0x00001555538d88a0  pixman_glyph_cache_create@plt
0x00001555538d88c0  pixman_image_get_component_alpha@plt
0x0000155553909b68  to_pixman_image
0x0000155553909fb0  _pixman_operator
0x000015555390ad46  _pixman_image_add_traps
0x000015555390b11d  _pixman_image_add_tristrip
0x0000155553910d6c  _pixman_transparent_image
0x0000155553910d84  _pixman_black_image
0x0000155553910d9c  _pixman_white_image
0x0000155553910db4  _pixman_image_for_color
0x0000155553910e30  _pixman_image_for_gradient
0x0000155553911352  _pixman_image_for_mesh
0x00001555539129e8  _pixman_image_set_properties
0x0000155553912fd2  _pixman_image_for_recording
0x0000155553913788  _pixman_image_for_surface
0x0000155553913e82  _pixman_image_for_raster
0x000015555391411c  _pixman_image_for_pattern
0x00001555539146cf  _cairo_format_from_pixman_format
0x0000155553914779  _cairo_content_from_pixman_format
0x000015555391492b  _cairo_image_surface_create_for_pixman_image
0x00001555539149aa  _pixman_format_from_masks
0x0000155553914b2b  _pixman_format_to_masks
0x0000155553914e74  _cairo_format_to_pixman_format_code
0x0000155553914ef0  _cairo_image_surface_create_with_pixman_format
0x000015555391db05  _cairo_matrix_to_pixman_matrix
0x000015555391de60  _pixman_nearest_sample
0x000015555391de93  _cairo_matrix_is_pixman_translation
0x000015555391e013  _cairo_matrix_to_pixman_matrix_offset
0x00001555539adf90  _cairo_xlib_display_get_xrender_format_for_pixman
0x00001555539bcf46  _pixman_format_for_xlib_surface
0x0000155553837880  _pixman_internal_only_get_implementation
0x0000155553837e60  pixman_edge_step
0x0000155553837ee0  pixman_edge_init
0x0000155553838060  pixman_line_fixed_edge_init
0x00001555538380b0  pixman_sample_floor_y
0x0000155553838190  pixman_sample_ceil_y
0x0000155553838260  pixman_image_create_solid_fill
0x0000155553838320  pixman_region32_selfcheck
0x00001555538384c0  pixman_region32_extents
0x00001555538384d0  pixman_region32_not_empty
0x00001555538384f0  pixman_region32_contains_point
0x0000155553838690  pixman_region32_clear
0x00001555538386d0  pixman_region32_reset
0x0000155553838760  pixman_region32_translate
0x00001555538387b0  pixman_region32_contains_rectangle
0x0000155553838a10  pixman_region32_inverse
0x0000155553838b50  pixman_region32_copy
0x0000155553838c70  pixman_region32_subtract
0x0000155553838d80  pixman_region32_union
0x0000155553838f30  pixman_region32_union_rect
0x0000155553838fe0  pixman_region32_intersect
0x00001555538391e0  pixman_region32_intersect_rect
0x0000155553839240  pixman_region32_rectangles
0x0000155553839270  pixman_region32_n_rects
0x0000155553839290  pixman_region32_fini
0x00001555538392b0  pixman_region32_init
0x00001555538392d0  pixman_region32_init_with_extents
0x0000155553839330  pixman_region32_init_rect
0x0000155553839390  pixman_region32_init_rects
0x0000155553839540  pixman_region32_equal
0x000015555383b060  pixman_region_set_static_pointers
0x000015555383b080  pixman_region_selfcheck
0x000015555383b220  pixman_region_extents
0x000015555383b230  pixman_region_not_empty
0x000015555383b250  pixman_region_contains_point
0x000015555383b410  pixman_region_clear
0x000015555383b450  pixman_region_reset
0x000015555383b4e0  pixman_region_translate
0x000015555383b810  pixman_region_contains_rectangle
0x000015555383baa0  pixman_region_inverse
0x000015555383bd30  pixman_rasterize_trapezoid
0x000015555383bea0  pixman_composite_trapezoids
0x000015555383c240  pixman_composite_triangles
0x000015555383c2e0  pixman_add_trapezoids
0x000015555383c360  pixman_add_triangles
0x000015555383c3c0  pixman_add_traps
0x000015555383c570  pixman_region32_init_from_image
0x000015555383cb80  pixman_region_init_from_image
0x000015555383d1e0  pixman_region_init_rects
0x000015555383d3a0  pixman_region_subtract
0x000015555383d4a0  pixman_region_union
0x000015555383d660  pixman_region_union_rect
0x000015555383d710  pixman_region_intersect
0x000015555383d930  pixman_region_intersect_rect
0x000015555383ec90  pixman_region_copy
0x000015555383ef00  pixman_region_rectangles
0x000015555383ef30  pixman_region_n_rects
0x000015555383ef50  pixman_region_fini
0x000015555383ef70  pixman_region_init
0x000015555383ef90  pixman_region_init_with_extents
0x000015555383eff0  pixman_region_init_rect
0x000015555383f050  pixman_region_equal
0x000015555383f170  pixman_f_transform_init_identity
0x000015555383f1c0  pixman_f_transform_init_translate
0x000015555383f210  pixman_f_transform_init_rotate
0x000015555383f260  pixman_f_transform_init_scale
0x000015555383f2b0  pixman_f_transform_multiply
0x000015555383f370  pixman_f_transform_translate
0x000015555383f430  pixman_f_transform_rotate
0x000015555383f4f0  pixman_f_transform_scale
0x000015555383f5f0  pixman_f_transform_point_3d
0x000015555383f690  pixman_f_transform_point
0x000015555383f760  pixman_f_transform_bounds
0x000015555383f9f0  pixman_f_transform_invert
0x000015555383fbd0  pixman_transform_from_pixman_f_transform
0x000015555383fcc0  pixman_f_transform_from_pixman_transform
0x000015555383fd10  pixman_transform_is_int_translate
0x000015555383fdc0  pixman_transform_is_scale
0x000015555383fe70  pixman_transform_is_identity
0x000015555383ff20  pixman_transform_invert
0x000015555383ff90  pixman_transform_init_translate
0x000015555383ffd0  pixman_transform_init_rotate
0x0000155553840000  pixman_transform_init_scale
0x0000155553840030  pixman_transform_multiply
0x0000155553840110  pixman_transform_is_inverse
0x0000155553840160  pixman_transform_translate
0x0000155553840210  pixman_transform_rotate
0x00001555538402c0  pixman_transform_scale
0x00001555538403a0  pixman_transform_init_identity
0x00001555538403d0  pixman_transform_point_31_16_3d
0x00001555538405f0  pixman_transform_point_3d
0x000015555384a670  pixman_transform_point_31_16_affine
0x000015555384a7d0  pixman_transform_point_31_16
0x000015555384b160  pixman_transform_point
0x000015555384b200  pixman_transform_bounds
0x000015555384b750  pixman_image_get_format
0x000015555384b770  pixman_image_get_depth
0x000015555384b7c0  pixman_image_get_stride
0x000015555384b7e0  pixman_image_get_height
0x000015555384b800  pixman_image_get_width
0x000015555384b820  pixman_image_get_data
0x000015555384b830  pixman_image_set_accessors
0x000015555384b8c0  pixman_image_get_component_alpha
0x000015555384b8d0  pixman_image_set_component_alpha
0x000015555384b8e0  pixman_image_set_indexed
0x000015555384b900  pixman_image_set_source_clipping
0x000015555384b910  pixman_image_set_filter
0x000015555384ba00  pixman_image_set_repeat
0x000015555384ba10  pixman_image_set_transform
0x000015555384bb40  pixman_image_set_has_client_clip
0x000015555384bb50  pixman_image_set_clip_region
0x000015555384c1a0  pixman_disable_out_of_bounds_workaround
0x000015555384c1b0  pixman_image_get_destroy_data
0x000015555384c1c0  pixman_image_set_destroy_function
0x000015555384c1d0  pixman_image_ref
0x000015555384c270  pixman_glyph_get_mask_format
0x000015555384c320  pixman_glyph_get_extents
0x000015555384c3f0  pixman_glyph_cache_lookup
0x000015555384c400  pixman_glyph_cache_freeze
0x000015555384c410  pixman_glyph_cache_create
0x000015555384c530  pixman_image_set_clip_region32
0x000015555384c610  pixman_image_create_radial_gradient
0x000015555384c760  pixman_image_create_linear_gradient
0x000015555384c8b0  pixman_image_unref
0x000015555384c8d0  pixman_image_set_alpha_map
0x000015555384c9b0  pixman_glyph_cache_remove
0x000015555384c9f0  pixman_glyph_cache_thaw
0x000015555384cac0  pixman_glyph_cache_destroy
0x000015555384cb30  pixman_glyph_cache_insert
0x000015555384cd60  pixman_composite_glyphs
0x000015555384d200  pixman_composite_glyphs_no_mask
0x00001555538654a0  pixman_rasterize_edges
0x0000155553866d90  pixman_filter_create_separable_convolution
0x0000155553866f90  pixman_image_create_conical_gradient
0x000015555387f370  pixman_image_create_bits_no_clear
0x000015555387f380  pixman_image_create_bits
0x00001555538875d0  pixman_format_supported_source
0x00001555538878a0  pixman_format_supported_destination
0x00001555538878d0  pixman_version_string
0x00001555538878e0  pixman_version
0x00001555538878f0  pixman_fill
0x0000155553887990  pixman_blt
0x00001555538888f0  pixman_compute_composite_region
0x0000155553888ac0  pixman_image_composite32
0x0000155553888fb0  pixman_image_fill_boxes
0x0000155553889340  pixman_image_fill_rectangles
0x0000155553889470  pixman_image_composite
```

I set a breakpoint on `` instead, which may help developers. This is my backtrace:

```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


Breakpoint 3, 0x0000155553839330 in pixman_region32_init_rect () from /usr/lib/libpixman-1.so.0
(gdb) bt
#0  0x0000155553839330 in pixman_region32_init_rect () at /usr/lib/libpixman-1.so.0
#1  0x000015555395a4a5 in cairo_region_create_rectangles () at /usr/lib/libcairo.so.2
#2  0x00001555538ef6d5 in _cairo_clip_extract_region () at /usr/lib/libcairo.so.2
#3  0x00001555538ef756 in _cairo_clip_get_region () at /usr/lib/libcairo.so.2
#4  0x0000155553983574 in clip_and_composite () at /usr/lib/libcairo.so.2
#5  0x00001555539855ee in clip_and_composite_traps () at /usr/lib/libcairo.so.2
#6  0x000015555398628f in _cairo_traps_compositor_stroke () at /usr/lib/libcairo.so.2
#7  0x00001555538f7104 in _cairo_compositor_stroke () at /usr/lib/libcairo.so.2
#8  0x00001555539bf9d4 in _cairo_xlib_surface_stroke () at /usr/lib/libcairo.so.2
#9  0x0000155553978ec1 in _cairo_surface_stroke () at /usr/lib/libcairo.so.2
#10 0x0000155553904b6b in _cairo_gstate_stroke () at /usr/lib/libcairo.so.2
#11 0x00001555538fbca8 in _cairo_default_context_stroke () at /usr/lib/libcairo.so.2
#12 0x000015555398f0af in cairo_stroke () at /usr/lib/libcairo.so.2
#13 0x0000155555099a66 in GGDKDrawDrawLine
    (w=0x555555a6e810, x=65, y=189, xend=58, yend=196, col=10066326) at ggdkcdraw.c:824
#14 0x00001555550181a0 in GDrawDrawLine
    (w=0x555555a6e810, x=65, y=189, xend=58, yend=196, col=10066326) at gdraw.c:411
#15 0x0000155555066d6c in draw_arrow (pixmap=0x555555a6e810, gsb=0x555555a7c170, which=3)
    at gscrollbar.c:249
#16 0x000015555506702e in gscrollbar_expose
    (pixmap=0x555555a6e810, g=0x555555a7c170, event=0x7fffffffb7c0) at gscrollbar.c:291
#17 0x0000155555013f4a in _GWidget_Container_eh (gw=0x555555a6e810, event=0x7fffffffb7c0)
    at gcontainer.c:287
#18 0x0000155555015f1e in _GWidget_TopLevel_eh (gw=0x555555a6e810, event=0x7fffffffb7c0)
    at gcontainer.c:745
#19 0x0000155555090cc2 in _GGDKDraw_CallEHChecked (gw=0x555555a6e810, event=0x7fffffffb7c0, eh=
    0x155555015590 <_GWidget_TopLevel_eh>) at ggdkdraw.c:335
#20 0x00001555550934e0 in _GGDKDraw_DispatchEvent (event=0x7fffffffb860, data=0x5555556573c0)
    at ggdkdraw.c:1210
#21 0x0000155553b4cc86 in  () at /usr/lib/libgdk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--c
#22 0x0000155553b5d8c0 in  () at /usr/lib/libgdk-3.so.0
#23 0x0000155553b5ea91 in  () at /usr/lib/libgdk-3.so.0
#24 0x0000155553b5ec55 in  () at /usr/lib/libgdk-3.so.0
#25 0x0000155552e30e75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#26 0x0000155552e1dfd5 in  () at /usr/lib/libgobject-2.0.so.0
#27 0x0000155552e221ae in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#28 0x0000155552e23080 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#29 0x0000155553b5666e in  () at /usr/lib/libgdk-3.so.0
#30 0x0000155553b40c3b in  () at /usr/lib/libgdk-3.so.0
#31 0x0000155552d42e53 in  () at /usr/lib/libglib-2.0.so.0
#32 0x0000155552d43661 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#33 0x0000155552d45739 in  () at /usr/lib/libglib-2.0.so.0
#34 0x0000155552d4577e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#35 0x00001555550960b0 in GGDKDrawEventLoop (gdisp=0x5555556573c0) at ggdkdraw.c:2190
#36 0x0000155555019486 in GDrawEventLoop (gdisp=0x5555556573c0) at gdraw.c:787
#37 0x00001555553a22ba in fontforge_main (argc=1, argv=0x7fffffffe1d8) at startui.c:1417
#38 0x0000555555555159 in main (argc=1, argv=0x7fffffffe1d8) at main.c:39

```

**Comment by kamiyaa** [comment]
Running into this issue as well.

Where all qt applications fail to open popups (such as file-choosers), rendering these apps basically useless.
Applications include: Google-chrome, Signal-desktop, Telegram-desktop, Brave browser, etc.

System: Gentoo Linux

```
*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
