### ISSUE TITLE
test118.pe fails on i686

### ISSUE THREAD

**Issue by mbakke** [fontforge/fontforge#3780]
When built for i686-linux, test118.pe "Test Unicode encodings" fails:

```
## ---------------------- ##
## Detailed failed tests. ##
## ---------------------- ##

#                             -*- compilation -*-
28. testsuite.at:108: testing Test Unicode encodings ...
./testsuite.at:108: (${abs_top_builddir}/fontforgeexe/fontforge -lang ff -script "${abs_srcdir}/test118.pe" "$test_input1" "$test_input2" "$test_input3" "$test_input4" "$test_input5" "$test_input6" "$test_input7" || false)
stderr:
Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 00:00 UTC  1-Jan-1970-ML-D.
 Based on source from git with hash: 
Failed to open hotkey definition file: /tmp/guix-build-fontforge-20190413.drv-0/fontforge-20190413/fontforgeexe/share/fontforge/hotkeys/default
Cannot find your hotkey definition file!
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Lookup subtable contains unused glyph uni0309 making the whole subtable invalid
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Sample Text string in the English (US) language.
The glyph named dotlessj is mapped to U+F6BE.
  But its name indicates it should be mapped to U+0237.
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Sample Text string in the English (US) language.
The glyph named dotlessj is mapped to U+F6BE.
  But its name indicates it should be mapped to U+0237.
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Sample Text string in the English (US) language.
The glyph named dotlessj is mapped to U+F6BE.
  But its name indicates it should be mapped to U+0237.
/tmp/guix-build-fontforge-20190413.drv-0/fontforge-20190413/tests/testsuite.dir/at-groups/28/test-source: line 44:  3382 Segmentation fault      ${abs_top_builddir}/fontforgeexe/fontforge -lang ff -script "${abs_srcdir}/test118.pe" "$test_input1" "$test_input2" "$test_input3" "$test_input4" "$test_input5" "$test_input6" "$test_input7"
stdout:
./testsuite.at:108: exit code was 1, expected 0
28. testsuite.at:108: 28. Test Unicode encodings (testsuite.at:108): FAILED (testsuite.at:108)
```

Any idea what is going on here, or how to debug this further?

**Comment by mbakke** [comment]
I managed to reduce the failure to a single command, which segfaults in [scripting.c:L10405](https://github.com/fontforge/fontforge/blob/20190413/fontforge/scripting.c#L10405):

```
./fontforgeexe/.libs/fontforge -lang ff -script ./tests/test118.pe ./tests/fonts/NimbusLGCUni-Regular.sfd
```

Here is a backtrace obtained with GDB:

```
#0  assign (c=c@entry=0xffffa3c4, val=val@entry=0xffffa0b4) at scripting.c:10405
#1  0xf77a1623 in expr (val=0xffffa0b4, c=0xffffa3c4) at scripting.c:10461
#2  ff_statement (c=0xffffa3c4) at scripting.c:10670
#3  0xf77a1f14 in doif (c=<optimized out>) at scripting.c:10600
#4  ff_statement (c=0xffffa3c4) at scripting.c:10646
#5  0xf77a1c59 in doif (c=<optimized out>) at scripting.c:10582
#6  ff_statement (c=0xffffa3c4) at scripting.c:10646
#7  0xf77a17a8 in dowhile (c=0xffffa3c4) at scripting.c:10543
#8  ff_statement (c=0xffffa3c4) at scripting.c:10642
#9  0xf77a22f9 in docall (c=c@entry=0xffffa854, name=0xffffa754 "\002", val=0xffffa854, val@entry=0xffffa754) at scripting.c:9706
#10 0xf77a3d85 in term (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10104
#11 0xf77a428b in mul (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10157
#12 0xf77a444b in add (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10202
#13 0xf77a47ab in comp (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10277
#14 0xf77a4a3a in _and (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10320
#15 0xf77a4bca in _or (val=0xffffa754, c=c@entry=0xffffa854) at scripting.c:10351
#16 assign (c=c@entry=0xffffa854, val=val@entry=0xffffa754) at scripting.c:10383
#17 0xf77a1623 in expr (val=0xffffa754, c=0xffffa854) at scripting.c:10461
#18 ff_statement (c=0xffffa854) at scripting.c:10670
#19 0xf77a59a0 in ProcessNativeScript (argc=6, argv=0xffffcc64, script=0x0) at scripting.c:10818
#20 0xf77a61c0 in _CheckIsScript (argv=0xffffcc64, argc=6) at scripting.c:10910
#21 CheckIsScript (argc=6, argv=0xffffcc64) at scripting.c:10947
#22 0xf7e4059a in fontforge_main (argc=6, argv=0xffffcc64) at startui.c:1104
#23 0x0804906b in main (argc=6, argv=0xffffcc64) at main.c:39
```

**Comment by jtanx** [comment]
Is this from latest master, or are you using the 20190403 tarball? If you're using the tarball, this is most likely fixed with #3715.

**Comment by mbakke** [comment]
@jtanx Thanks for the quick reply.  I am indeed using the 20190403 release, and can confirm that #3715 fixes the issue.

Do you know whether it is safe to pick these patches to the 20190403 tarball?

**Comment by jtanx** [comment]
@mbakke thanks for confirming. I don't see any issues to patching it.
