### ISSUE TITLE
Reverting a file from the charview can lead to a segfault

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#3807]
* Start with a new file
* Save it
* Open a charview
* Select 'Revert file' -> crash

Backtrace line numbers may not be accurate (working off a development branch).

`test` is NULL.

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004c4b60 in CVUnlinkView (cv=0xcd0820)
    at ../fontforgeexe/charview.c:3432
3432                    test->b.next!=(CharViewBase *) cv && test->b.next!=NULL;
(gdb) bt
#0  0x00000000004c4b60 in CVUnlinkView (cv=0xcd0820)
    at ../fontforgeexe/charview.c:3432
#1  cv_e_h (gw=0xd17980, event=0x7fffffffd0c0)
    at ../fontforgeexe/charview.c:6352
#2  0x000000000042eea8 in _GWidget_Container_eh (gw=gw@entry=0xd17980, 
    event=event@entry=0x7fffffffd0c0) at ../gdraw/gcontainer.c:405
```

**Comment by skef** [comment]
This doesn't reproduce for me right now unless I'm misinterpreting the instructions. 

@jtanx could you try this one out again?

**Comment by jtanx** [comment]
Odd, yeah I can't repro this any more.
