### ISSUE TITLE
Crash while switching back and forth between different CID's

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3935]
(Note: The same font as in #3934 is causing this problem.)

```
double free or corruption (out)

Program received signal SIGABRT, Aborted.
0x0000155553a6b755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553a6b755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553a56851 in abort () at /usr/lib/libc.so.6
#2  0x0000155553aada38 in __libc_message () at /usr/lib/libc.so.6
#3  0x0000155553ab425a in  () at /usr/lib/libc.so.6
#4  0x0000155553ab5c50 in _int_free () at /usr/lib/libc.so.6
#5  0x00001555551253e9 in EncMapFree (map=0x5555615f2200) at fontforge/splineutil.c:6310
#6  0x0000555555676aa8 in FVShowSubFont (fv=0x555555a0ac10, new=0x555555c8f200) at fontforgeexe/fontview.c:2920
#7  0x000055555574c0b4 in gmenu_mouse (m=0x555561a537a0, event=0x7fffffffcca0) at gdraw/gmenu.c:948
#8  0x000055555574b07a in gmenu_eh (w=0x555555d38700, ge=0x7fffffffcca0) at gdraw/gmenu.c:1389
#9  0x0000555555737494 in _GGDKDraw_CallEHChecked (gw=<optimized out>, event=0x4, eh=0x0) at gdraw/ggdkdraw.c:323
#10 0x0000555555737494 in _GGDKDraw_DispatchEvent (event=<optimized out>, data=<optimized out>) at gdraw/ggdkdraw.c:1221
#11 0x00001555542cf8b4 in  () at /usr/lib/libgdk-3.so.0
#12 0x000015555427c904 in  () at /usr/lib/libgdk-3.so.0
#13 0x0000155553c603ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x0000155553c621c1 in  () at /usr/lib/libglib-2.0.so.0
#15 0x0000155553c62201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x000055555573a4e6 in GGDKDrawEventLoop (gdisp=0x555555a69e90) at gdraw/ggdkdraw.c:2187
#17 0x00005555557084f8 in fontforge_main (argc=<optimized out>, argv=<optimized out>) at fontforgeexe/startui.c:1416
#18 0x0000155553a57ee3 in __libc_start_main () at /usr/lib/libc.so.6
#19 0x00005555555aba0e in _start ()
```

Simple reproduction:

* Open [蒙纳简版黑.otf](https://github.com/fontforge/fontforge/files/3629472/default.zip)
* Encoding&rarr;Compact
* Switch CID to CHei3HK-BoldSupp
* Switch CID back to CHei3HK-Bold-Roman
* You should experience a crash

Alternate backtraces:

```
malloc(): unsorted double linked list corrupted

Program received signal SIGABRT, Aborted.
0x0000155553a6b755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553a6b755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553a56851 in abort () at /usr/lib/libc.so.6
#2  0x0000155553aada38 in __libc_message () at /usr/lib/libc.so.6
#3  0x0000155553ab425a in  () at /usr/lib/libc.so.6
#4  0x0000155553ab70cc in _int_malloc () at /usr/lib/libc.so.6
#5  0x0000155553ab9486 in calloc () at /usr/lib/libc.so.6
#6  0x0000155554f7ce62 in CIDSetEncMap (fv=0x555555c6ac00, new=0x555555d0e660) at fontforge/fontviewbase.c:1224
#7  0x0000555555676b06 in FVShowSubFont (fv=0x555555c6ac00, new=0x555555d0e660) at fontforgeexe/fontview.c:2927
#8  0x000055555574c0b4 in gmenu_mouse (m=0x555555d70ad0, event=0x7fffffffcca0) at gdraw/gmenu.c:948
#9  0x000055555574b07a in gmenu_eh (w=0x5555561d3390, ge=0x7fffffffcca0) at gdraw/gmenu.c:1389
#10 0x0000555555737494 in _GGDKDraw_CallEHChecked (gw=<optimized out>, event=0x4, eh=0x0) at gdraw/ggdkdraw.c:323
#11 0x0000555555737494 in _GGDKDraw_DispatchEvent (event=<optimized out>, data=<optimized out>) at gdraw/ggdkdraw.c:1221
#12 0x00001555542cf8b4 in  () at /usr/lib/libgdk-3.so.0
#13 0x000015555427c904 in  () at /usr/lib/libgdk-3.so.0
#14 0x0000155553c603ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x0000155553c621c1 in  () at /usr/lib/libglib-2.0.so.0
#16 0x0000155553c62201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x000055555573a4e6 in GGDKDrawEventLoop (gdisp=0x555555a69a10) at gdraw/ggdkdraw.c:2187
#18 0x00005555557084f8 in fontforge_main (argc=<optimized out>, argv=<optimized out>) at fontforgeexe/startui.c:1416
#19 0x0000155553a57ee3 in __libc_start_main () at /usr/lib/libc.so.6
#20 0x00005555555aba0e in _start ()
```

```
double free or corruption (!prev)

Program received signal SIGABRT, Aborted.
0x0000155553a6b755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553a6b755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553a56851 in abort () at /usr/lib/libc.so.6
#2  0x0000155553aada38 in __libc_message () at /usr/lib/libc.so.6
#3  0x0000155553ab425a in  () at /usr/lib/libc.so.6
#4  0x0000155553ab5c5c in _int_free () at /usr/lib/libc.so.6
#5  0x0000155554f6147c in CompactEncMap (map=0x555555cad2e0, sf=0x555555d0ed40) at fontforge/encoding.c:2131
#6  0x0000555555676b24 in FVShowSubFont (fv=0x555555cf8a00, new=0x555555d0ed40) at fontforgeexe/fontview.c:2930
#7  0x000055555574c0b4 in gmenu_mouse (m=0x5555561d6490, event=0x7fffffffcca0) at gdraw/gmenu.c:948
#8  0x000055555574b07a in gmenu_eh (w=0x555555d0ebb0, ge=0x7fffffffcca0) at gdraw/gmenu.c:1389
#9  0x0000555555737494 in _GGDKDraw_CallEHChecked (gw=<optimized out>, event=0x4, eh=0x0) at gdraw/ggdkdraw.c:323
#10 0x0000555555737494 in _GGDKDraw_DispatchEvent (event=<optimized out>, data=<optimized out>) at gdraw/ggdkdraw.c:1221
#11 0x00001555542cf8b4 in  () at /usr/lib/libgdk-3.so.0
#12 0x000015555427c904 in  () at /usr/lib/libgdk-3.so.0
#13 0x0000155553c603ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x0000155553c621c1 in  () at /usr/lib/libglib-2.0.so.0
#15 0x0000155553c62201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x000055555573a4e6 in GGDKDrawEventLoop (gdisp=0x555555a68340) at gdraw/ggdkdraw.c:2187
#17 0x00005555557084f8 in fontforge_main (argc=<optimized out>, argv=<optimized out>) at fontforgeexe/startui.c:1416
#18 0x0000155553a57ee3 in __libc_start_main () at /usr/lib/libc.so.6
#19 0x00005555555aba0e in _start ()

```

**Comment by ctrlcctrlv** [comment]
Valgrind:

```
Recovering from /home/fred/.config/fontforge/autosave/auto0199a6-1.asfd... ==105069== Invalid write of size 4
==105069==    at 0x49B1539: CIDSetEncMap (fontviewbase.c:1219)
==105069==    by 0x2B1311: FVShowSubFont (fontview.c:2927)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D0200: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==  Address 0x2122c990 is 0 bytes after a block of size 75,648 alloc'd
==105069==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==105069==    by 0x4C0F599: EncMapCopy (splineutil.c:6323)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069== 
==105069== Invalid read of size 8
==105069==    at 0x483F924: memmove (vg_replace_strmem.c:1270)
==105069==    by 0x4C0F60E: EncMapCopy (splineutil.c:6325)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==  Address 0x2122c990 is 0 bytes after a block of size 75,648 alloc'd
==105069==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==105069==    by 0x4C0F599: EncMapCopy (splineutil.c:6323)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069== 
==105069== Invalid read of size 8
==105069==    at 0x483F92F: memmove (vg_replace_strmem.c:1270)
==105069==    by 0x4C0F60E: EncMapCopy (splineutil.c:6325)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==  Address 0x2122c998 is 8 bytes after a block of size 75,648 alloc'd
==105069==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==105069==    by 0x4C0F599: EncMapCopy (splineutil.c:6323)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069== 
==105069== Invalid read of size 8
==105069==    at 0x483F937: memmove (vg_replace_strmem.c:1270)
==105069==    by 0x4C0F60E: EncMapCopy (splineutil.c:6325)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==  Address 0x2122c9a0 is 16 bytes after a block of size 75,648 alloc'd
==105069==    at 0x483877F: malloc (vg_replace_malloc.c:299)
==105069==    by 0x4C0F599: EncMapCopy (splineutil.c:6323)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069== 

valgrind: m_mallocfree.c:307 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 75712, hi = 81256486291942.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.


host stacktrace:
==105069==    at 0x58048114: show_sched_status_wrk (m_libcassert.c:369)
==105069==    by 0x58048227: report_and_quit (m_libcassert.c:440)
==105069==    by 0x580483B9: vgPlain_assert_fail (m_libcassert.c:506)
==105069==    by 0x58052490: get_bszB_as_is (m_mallocfree.c:305)
==105069==    by 0x58052490: get_bszB (m_mallocfree.c:315)
==105069==    by 0x58052490: get_pszB (m_mallocfree.c:389)
==105069==    by 0x58052490: vgPlain_describe_arena_addr (m_mallocfree.c:1592)
==105069==    by 0x5803DEDA: vgPlain_describe_addr (m_addrinfo.c:187)
==105069==    by 0x5803CD46: vgMemCheck_update_Error_extra (mc_errors.c:1187)
==105069==    by 0x58041E24: vgPlain_maybe_record_error (m_errormgr.c:823)
==105069==    by 0x5803C1CB: vgMemCheck_record_address_error (mc_errors.c:767)
==105069==    by 0x58011274: mc_LOADVn_slow (mc_main.c:1553)
==105069==    by 0x1003E5DFA9: ???
==105069==    by 0x1003252F2F: ???
==105069==    by 0x100200834F: ???
==105069==    by 0x1003252F17: ???
==105069==    by 0x1003252F2F: ???
==105069==    by 0x1003252F3F: ???
==105069==    by 0x201: ???
==105069==    by 0x1002008727: ???
==105069==    by 0x10032527F7: ???

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 105069)
==105069==    at 0x483F93F: memmove (vg_replace_strmem.c:1270)
==105069==    by 0x4C0F60E: EncMapCopy (splineutil.c:6325)
==105069==    by 0x2B1327: FVShowSubFont (fontview.c:2929)
==105069==    by 0x2B3D3B: FVMenuShowSubFont (fontview.c:3633)
==105069==    by 0x432C09: gmenu_mouse (gmenu.c:948)
==105069==    by 0x4346CC: gmenu_eh (gmenu.c:1389)
==105069==    by 0x414523: _GGDKDraw_CallEHChecked (ggdkdraw.c:329)
==105069==    by 0x416F46: _GGDKDraw_DispatchEvent (ggdkdraw.c:1232)
==105069==    by 0x5BDD8B3: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x5B8A903: ??? (in /usr/lib/libgdk-3.so.0.2406.4)
==105069==    by 0x61CE3AD: g_main_context_dispatch (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D01C0: ??? (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x61D0200: g_main_context_iteration (in /usr/lib/libglib-2.0.so.0.6200.0)
==105069==    by 0x419C71: GGDKDrawEventLoop (ggdkdraw.c:2190)
==105069==    by 0x405778: GDrawEventLoop (gdraw.c:789)
==105069==    by 0x3C9B28: fontforge_main (startui.c:1415)
==105069==    by 0x15EB28: main (main.c:33)
client stack range: [0x1FFEFE8000 0x1FFF000FFF] client SP: 0x1FFEFFEB78
valgrind stack range: [0x1003153000 0x1003252FFF] top usage: 13504 of 1048576
```

**Comment by ctrlcctrlv** [comment]
I was able to cause a slightly different crash by trying to un-compact the encoding before switching, then recompacting after, which allows a switch but causes a crash on compacting.
```
double free or corruption (!prev)

Program received signal SIGABRT, Aborted.
0x0000155553958755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553958755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553943851 in abort () at /usr/lib/libc.so.6
#2  0x000015555399aa38 in __libc_message () at /usr/lib/libc.so.6
#3  0x00001555539a125a in  () at /usr/lib/libc.so.6
#4  0x00001555539a2c5c in _int_free () at /usr/lib/libc.so.6
#5  0x0000155554e666fa in CompactEncMap (map=0x555555d5f980, sf=0x555555dd32b0) at fontforge/encoding.c:2131
#6  0x0000155554e8bcfe in FVCompact (fv=0x555555d5f800) at fontforge/fontviewbase.c:1537
#7  0x0000555555703658 in FVMenuCompact (gw=0x555555daf0e0, UNUSED_mi=0x555555f71500, UNUSED_e=0x7fffffffcc00)
    at fontforgeexe/fontview.c:4803
#8  0x000055555587ec0a in gmenu_mouse (m=0x555560b73490, event=0x7fffffffcc00) at gdraw/gmenu.c:948
#9  0x00005555558806cd in gmenu_eh (w=0x55555600ee70, ge=0x7fffffffcc00) at gdraw/gmenu.c:1389
#10 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x55555600ee70, event=0x7fffffffcc00, eh=0x5555558805f4 <gmenu_eh>)
    at gdraw/ggdkdraw.c:329
#11 0x0000555555862f47 in _GGDKDraw_DispatchEvent (event=0x5555560538e0, data=0x555555c0e6e0) at gdraw/ggdkdraw.c:1232
#12 0x00001555541bc8b4 in  () at /usr/lib/libgdk-3.so.0
#13 0x0000155554169904 in  () at /usr/lib/libgdk-3.so.0
#14 0x0000155553b4d3ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
#16 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x0000555555865c72 in GGDKDrawEventLoop (gdisp=0x555555c0e6e0) at gdraw/ggdkdraw.c:2190
#18 0x0000555555851779 in GDrawEventLoop (gdisp=0x555555c0e6e0) at gdraw/gdraw.c:789
#19 0x0000555555815b29 in fontforge_main (argc=2, argv=0x7fffffffe038) at fontforgeexe/startui.c:1415
#20 0x00005555555aab29 in main (argc=2, argv=0x7fffffffe038) at fontforgeexe/main.c:33
```
