### ISSUE TITLE
[CID] Hovering over OpenType lookup info row in CID fonts causes a crash

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3937]
Wow, this CID code is truly _here be dragons_. Usually FontForge is really stable, but its CID implementation is nigh unusable.

(Note: The font causing the crash is the same one in #3934 and #3935.)

```
Program received signal SIGSEGV, Segmentation fault.
0x00001555550a7d5d in SCDrawsSomething (sc=0x127a1) at fontforge/splinesaveafm.c:1061
1061        for ( layer = 0; layer<sc->layer_cnt; ++layer ) if ( !sc->layers[layer].background ) {
(gdb) bt
#0  0x00001555550a7d5d in SCDrawsSomething (sc=0x127a1) at fontforge/splinesaveafm.c:1061
#1  0x00001555550a7eb2 in SCWorthOutputting (sc=0x127a1) at fontforge/splinesaveafm.c:1091
#2  0x000015555513fc50 in AssignTTFGlyph (gi=0x7fffffffa3d8, sf=0x555555dd2c00, map=0x555555d5d780, iscff=1) at fontforge/tottf.c:1409
#3  0x0000155555154af2 in dumpcff (at=0x7fffffff96b0, sf=0x555555dd2c00, format=ff_cff, cff=0x55555618f200) at fontforge/tottf.c:6017
#4  0x000015555515568c in _WriteTTFFont
    (ttf=0x55555618f200, sf=0x555555dd2c00, format=ff_cff, bsizes=0x0, bf=bf_none, flags=16777216, map=0x555555d5d780, layer=1)
    at fontforge/tottf.c:6141
#5  0x0000155554e8eece in __FreeTypeFontContext
    (context=0x555555dda6e0, sf=0x555555dd2c00, sc=0x55555633f3c0, fv=0x555555d5d600, layer=1, ff=ff_cff, flags=16777216, shared_ftc=0x0) at fontforge/freetype.c:267
#6  0x0000155554e8f4db in _FreeTypeFontContext
    (sf=0x555555dd2c00, sc=0x55555633f3c0, fv=0x555555d5d600, layer=1, ff=ff_cff, flags=0, shared_ftc=0x0) at fontforge/freetype.c:364
#7  0x0000155554e92f98 in FreeTypeFontContext (sf=0x555555dd2c00, sc=0x55555633f3c0, fv=0x555555d5d600, layer=1)
    at fontforge/freetype.c:1147
#8  0x00005555555d97a1 in Rasterize (sc=0x55555633f3c0, def_layer=1) at fontforgeexe/charinfo.c:2816
#9  0x00005555555dcbb2 in NameList_GetImage
    (sf=0x55555602b900, sc=0x5555560f7e70, def_layer=1, namelist=0x555560b55120 "CNS1.520 CNS1.510", isliga=0)
    at fontforgeexe/charinfo.c:3273
#10 0x00005555555dd553 in PST_GetImage
    (pstk=0x555560b54c30, sf=0x55555602b900, def_layer=1, sub=0x555555bf7220, popup_r=4, sc=0x5555560f7e70)
    at fontforgeexe/charinfo.c:3383
#11 0x00005555557415cb in _PST_GetImage (_pstkd=0x7fffffffaeb0) at fontforgeexe/lookupui.c:2592
#12 0x000055555585c898 in GGadgetPopupTest (e=0x7fffffffabd0) at gdraw/ggadgets.c:564
#13 0x000055555585cdad in msgpopup_eh (popup=0x5555560c5d80, event=0x7fffffffabd0) at gdraw/ggadgets.c:640
#14 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x5555560c5d80, event=0x7fffffffabd0, eh=0x55555585cbe9 <msgpopup_eh>)
    at gdraw/ggdkdraw.c:329
#15 0x0000555555861cbb in _GGDKDraw_ProcessTimerEvent (user_data=0x555555dfc4a0) at gdraw/ggdkdraw.c:845
#16 0x0000155553b4ca74 in  () at /usr/lib/libglib-2.0.so.0
#17 0x0000155553b4d27f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x0000555555865bf6 in GGDKDrawProcessOneEvent (gdisp=0x555555c0e4f0) at gdraw/ggdkdraw.c:2179
#21 0x000055555585169c in GDrawProcessOneEvent (gdisp=0x555555c0e4f0) at gdraw/gdraw.c:769
#22 0x000055555574d02f in PSTKernD (sf=0x55555602b900, sub=0x555555bf7220, def_layer=1) at fontforgeexe/lookupui.c:5024
#23 0x000055555575219f in _LookupSubtableContents (sf=0x55555602b900, sub=0x555555bf7220, sd=0x0, def_layer=1)
    at fontforgeexe/lookupui.c:6010
#24 0x00005555556cdd65 in LookupSubtableContents (gfi=0x555556025880, isgpos=0) at fontforgeexe/fontinfo.c:6023
#25 0x00005555556cde20 in GFI_LookupEditSubtableContents (g=0x55555607a9d0, e=0x7fffffffc980) at fontforgeexe/fontinfo.c:6036
#26 0x000055555584045d in GButtonInvoked (b=0x55555607a9d0, ev=0x7fffffffcc00) at gdraw/gbuttons.c:257
#27 0x00005555558413d4 in gbutton_mouse (g=0x55555607a9d0, event=0x7fffffffcc00) at gdraw/gbuttons.c:485
#28 0x000055555584b99c in _GWidget_Container_eh (gw=0x555556076100, event=0x7fffffffcc00) at gdraw/gcontainer.c:304
#29 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x555556076100, event=0x7fffffffcc00, eh=0x55555584b5bb <_GWidget_Container_eh>)
    at gdraw/ggdkdraw.c:329
#30 0x0000555555862f47 in _GGDKDraw_DispatchEvent (event=0x5555560b6b30, data=0x555555c0e4f0) at gdraw/ggdkdraw.c:1232
#31 0x00001555541bc8b4 in  () at /usr/lib/libgdk-3.so.0
#32 0x0000155554169904 in  () at /usr/lib/libgdk-3.so.0
#33 0x0000155553b4d3ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#34 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
#35 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#36 0x0000555555865c72 in GGDKDrawEventLoop (gdisp=0x555555c0e4f0) at gdraw/ggdkdraw.c:2190
#37 0x0000555555851779 in GDrawEventLoop (gdisp=0x555555c0e4f0) at gdraw/gdraw.c:789
#38 0x0000555555815b29 in fontforge_main (argc=2, argv=0x7fffffffe038) at fontforgeexe/startui.c:1415
#39 0x00005555555aab29 in main (argc=2, argv=0x7fffffffe038) at fontforgeexe/main.c:33
```

Reproduction steps:
1. No cidmap file, &laquo;Give up&raquo;
1. CID menu, CID Font Info&hellip;
1. Lookups
1. Select any lookup, e.g. `'nalt' Alternate Annotation Forms lookup 12`
1. Select subtable under lookup, then &laquo;Edit Data&raquo;
1. Hover over any row
1. FontForge crashes

**Comment by ctrlcctrlv** [comment]
I got some more information by applying a simple patch:

```diff
diff --git a/fontforge/tottf.c b/fontforge/tottf.c
index b179c0f9e..404c1b2c1 100644
--- a/fontforge/tottf.c
+++ b/fontforge/tottf.c
@@ -1404,7 +1404,7 @@ static int AssignTTFGlyph(struct glyphinfo *gi,SplineFont *sf,EncMap *map,int is
     AssignNotdefNull(sf,bygid,iscff);
 
     j = iscff ? 1 : 3;
-    for ( i=0; i<map->enccount; ++i ) if ( map->map[i]!=-1 ) {
+    for ( i=0; i<map->enccount; ++i ) if ( map->map[i]!=-1 && i<=sf->glyphcnt ) {
        SplineChar *sc = sf->glyphs[map->map[i]];
        if ( SCWorthOutputting(sc) && sc->ttf_glyph==-1
 #if HANYANG
```


```
==116207==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x155547878700 at pc 0x155554275533 bp 0x7fffffff8360 sp 0x7fffffff8350
READ of size 8 at 0x155547878700 thread T0
    #0 0x155554275532 in AssignTTFGlyph fontforge/tottf.c:1408
    #1 0x1555542b13c6 in dumpcff fontforge/tottf.c:6017
    #2 0x1555542b2fe8 in _WriteTTFFont fontforge/tottf.c:6141
    #3 0x155553b91ae1 in __FreeTypeFontContext fontforge/freetype.c:267
    #4 0x155553b92a74 in _FreeTypeFontContext fontforge/freetype.c:364
    #5 0x155553b9d94f in FreeTypeFontContext fontforge/freetype.c:1147
    #6 0x55555573bd46 in Rasterize fontforgeexe/charinfo.c:2816
    #7 0x555555744361 in NameList_GetImage fontforgeexe/charinfo.c:3273
    #8 0x555555745de4 in PST_GetImage fontforgeexe/charinfo.c:3383
    #9 0x555555b13045 in _PST_GetImage fontforgeexe/lookupui.c:2592
    #10 0x555555e02522 in GGadgetPopupTest gdraw/ggadgets.c:564
    #11 0x555555e02ed8 in msgpopup_eh gdraw/ggadgets.c:640
    #12 0x555555e0dc2f in _GGDKDraw_CallEHChecked gdraw/ggdkdraw.c:329
    #13 0x555555e125ad in _GGDKDraw_ProcessTimerEvent gdraw/ggdkdraw.c:845
    #14 0x155552578a73  (/usr/lib/libglib-2.0.so.0+0x69a73)
    #15 0x15555257927e in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x6a27e)
    #16 0x15555257b1c0  (/usr/lib/libglib-2.0.so.0+0x6c1c0)
    #17 0x15555257b200 in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x6c200)
    #18 0x555555e1dc1f in GGDKDrawProcessOneEvent gdraw/ggdkdraw.c:2179
    #19 0x555555de5995 in GDrawProcessOneEvent gdraw/gdraw.c:769
    #20 0x555555b30a6e in PSTKernD fontforgeexe/lookupui.c:5024
    #21 0x555555b3e5da in _LookupSubtableContents fontforgeexe/lookupui.c:6010
    #22 0x5555559d25e2 in LookupSubtableContents fontforgeexe/fontinfo.c:6023
    #23 0x5555559e6977 in LookupMouse fontforgeexe/fontinfo.c:7418
    #24 0x5555559e71db in lookups_e_h fontforgeexe/fontinfo.c:7462
    #25 0x5555559e73dd in gsublookups_e_h fontforgeexe/fontinfo.c:7481
    #26 0x555555dddad5 in drawable_e_h gdraw/gdrawable.c:217
    #27 0x555555dd4d51 in _GWidget_Container_eh gdraw/gcontainer.c:405
    #28 0x555555e0dc2f in _GGDKDraw_CallEHChecked gdraw/ggdkdraw.c:329
    #29 0x555555e16c8a in _GGDKDraw_DispatchEvent gdraw/ggdkdraw.c:1232
    #30 0x155552bea8b3  (/usr/lib/libgdk-3.so.0+0x948b3)
    #31 0x155552b97903  (/usr/lib/libgdk-3.so.0+0x41903)
    #32 0x1555525793ad in g_main_context_dispatch (/usr/lib/libglib-2.0.so.0+0x6a3ad)
    #33 0x15555257b1c0  (/usr/lib/libglib-2.0.so.0+0x6c1c0)
    #34 0x15555257b200 in g_main_context_iteration (/usr/lib/libglib-2.0.so.0+0x6c200)
    #35 0x555555e1dcc2 in GGDKDrawEventLoop gdraw/ggdkdraw.c:2190
    #36 0x555555de5bce in GDrawEventLoop gdraw/gdraw.c:789
    #37 0x555555d432b1 in fontforge_main fontforgeexe/startui.c:1415
    #38 0x5555556b6d88 in main fontforgeexe/main.c:33
    #39 0x155552372ee2 in __libc_start_main (/usr/lib/libc.so.6+0x26ee2)
    #40 0x5555556b6c9d in _start (/home/fred/Workspace/fontforge2/bin/fontforge+0x162c9d)

0x155547878700 is located 0 bytes to the right of 151296-byte region [0x155547853800,0x155547878700)
allocated by thread T0 here:
    #0 0x155554b83ce8 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x155553b9121e in __FreeTypeFontContext fontforge/freetype.c:206
    #2 0x155553b92a74 in _FreeTypeFontContext fontforge/freetype.c:364
    #3 0x155553b9d94f in FreeTypeFontContext fontforge/freetype.c:1147
    #4 0x55555573bd46 in Rasterize fontforgeexe/charinfo.c:2816
    #5 0x555555744361 in NameList_GetImage fontforgeexe/charinfo.c:3273
    #6 0x555555745de4 in PST_GetImage fontforgeexe/charinfo.c:3383
    #7 0x555555b13045 in _PST_GetImage fontforgeexe/lookupui.c:2592
    #8 0x555555e02522 in GGadgetPopupTest gdraw/ggadgets.c:564
    #9 0x555555e02ed8 in msgpopup_eh gdraw/ggadgets.c:640
    #10 0x555555e0dc2f in _GGDKDraw_CallEHChecked gdraw/ggdkdraw.c:329
    #11 0x555555e125ad in _GGDKDraw_ProcessTimerEvent gdraw/ggdkdraw.c:845
    #12 0x155552578a73  (/usr/lib/libglib-2.0.so.0+0x69a73)

SUMMARY: AddressSanitizer: heap-buffer-overflow fontforge/tottf.c:1408 in AssignTTFGlyph
Shadow bytes around the buggy address:
  0x02ab28f07090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02ab28f070a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02ab28f070b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02ab28f070c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x02ab28f070d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x02ab28f070e0:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x02ab28f070f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x02ab28f07100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x02ab28f07110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x02ab28f07120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x02ab28f07130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
[...]
==116207==ABORTING

```

**Comment by frank-trampe** [comment]
I don't understand. You mean it runs farther as a result of the patch and then crashes somewhere else? This might just be because the extra check puts most of the glyphs out of bounds and thus skips the problematic one entirely. Does the same glyph cause the crash every time? What is its glyph number, and where is it in the encoding?

**Comment by ctrlcctrlv** [comment]
@frank-trampe The problematic `i` is always 1 greater than `sf->glyphcnt`. Adding a check for that causes the ASan output I posted.

**Comment by skef** [comment]
The immediate problem here is that the `sf->glyphcnt` goes to 18950 and the map goes to 18965. 

That problem traces all the way up the stack to `charinfo.c:Rasterize()`, where this is called:

```
    freetypecontext = FreeTypeFontContext(sc->parent,sc,sc->parent->fv,def_layer);
``` 
`sc->parent` is (named) `CHei3HKS-BoldSupp`. `sc->parent->fv->sf` is (named) `CHei3HKS-Bold-Roman`. Since the map is extracted from `sc->parent->fv, this code has the effect of causing Bold-Roman's map to be used with BoldSupp. 

Now, how did BoldSupp come into this anyway? `NameList_GetImage`, one level up, is called with the parent font. But `charinfo.c` line 3265 `SFGetChar(sf, -1, start)` is returning a glyph in BoldSupp. So that's the essence of the problem.

I tried adapting `freetype.c:__FreeTypeFontContext()` to get a map this way:
```
    if (fv!=NULL && fv->sf==sf)
        map = fv->map;
    else if (sf->fv!=NULL && sf->fv->sf==sf)
        map = sf->fv->map;
    else
        map = sf->map;
```
but the first two options don't match and the last is NULL. If there isn't a matching `fv` handy and `sf-map` is null, you might just have to build one here. With luck you can just assign it to `sf->map` so it can be reused and will eventually be deleted, although both of those would have to be confirmed.
