### ISSUE TITLE
Memory corruption followed by a crash in Metrics View of compact CID-keyed font

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3946]
Necessary file: [U-OTF-ShinGoUpr-Heavy.otf](https://github.com/fontforge/fontforge/files/3638372/U-OTF-ShinGoUpr-Heavy.zip)

```
#0  0x0000155553958755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553943851 in abort () at /usr/lib/libc.so.6
#2  0x000015555399aa38 in __libc_message () at /usr/lib/libc.so.6
#3  0x00001555539a125a in  () at /usr/lib/libc.so.6
#4  0x00001555539a508c in _int_realloc () at /usr/lib/libc.so.6
#5  0x00001555539a602f in realloc () at /usr/lib/libc.so.6
#6  0x0000155554e670ce in MapAddEncodingSlot (map=0x555555e03e90, gid=1047) at fontforge/encoding.c:2317
#7  0x0000155554e6714d in FVAddEncodingSlot (fv=0x555555e03d10, gid=1047) at fontforge/encoding.c:2328
#8  0x0000155554e6741c in MapAddEnc
    (sf=0x5555563bdce0, sc=0x555555eddb50, basemap=0x555555e03e90, map=0x555555e03e90, baseenc=1047, gid=1047, fv=0x555555e03d10)
    at fontforge/encoding.c:2370
#9  0x0000155554e67942 in SFAddGlyphAndEncode (sf=0x5555563bdce0, sc=0x555555eddb50, basemap=0x555555e03e90, baseenc=1047) at fontforge/encoding.c:2435
#10 0x00001555550661dc in _SFMakeChar (sf=0x5555563bdce0, map=0x555555e03e90, enc=1047) at fontforge/splinefont.c:223
#11 0x0000155555066309 in SFMakeChar (sf=0x5555563bdce0, map=0x555555e03e90, enc=1047) at fontforge/splinefont.c:243
#12 0x000055555576e42b in MVSCFromUnicode (mv=0x555556324ec0, sf=0x5555563bdce0, map=0x555555e03e90, ch=957, bdf=0x0) at fontforgeexe/metricsview.c:1615
#13 0x000055555576fc4c in MVTextChanged (mv=0x555556324ec0) at fontforgeexe/metricsview.c:1977
#14 0x0000555555770376 in MV_TextChanged (g=0x5555560040c0, e=0x7fffffffc650) at fontforgeexe/metricsview.c:2100
#15 0x00005555558af987 in GTextFieldChanged (gt=0x5555560040c0, src=-1) at gdraw/gtextfield.c:213
#16 0x00005555558b7919 in gtextfield_key (g=0x5555560040c0, event=0x7fffffffc930) at gdraw/gtextfield.c:1860
#17 0x000055555584c928 in _GWidget_TopLevel_Key (top=0x555555e97d80, ew=0x555555e97d80, event=0x7fffffffc930) at gdraw/gcontainer.c:518
#18 0x000055555584d33f in _GWidget_TopLevel_eh (gw=0x555555e97d80, event=0x7fffffffc930) at gdraw/gcontainer.c:682
#19 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x555555e97d80, event=0x7fffffffc930, eh=0x55555584ce8e <_GWidget_TopLevel_eh>)
    at gdraw/ggdkdraw.c:329
#20 0x0000555555862f47 in _GGDKDraw_DispatchEvent (event=0x555555c00330, data=0x555555c1aeb0) at gdraw/ggdkdraw.c:1232
#21 0x00001555541bc8b4 in  () at /usr/lib/libgdk-3.so.0
#22 0x0000155554169904 in  () at /usr/lib/libgdk-3.so.0
#23 0x0000155553b4d3ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
#25 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#26 0x0000555555865c72 in GGDKDrawEventLoop (gdisp=0x555555c1aeb0) at gdraw/ggdkdraw.c:2190
#27 0x0000555555851779 in GDrawEventLoop (gdisp=0x555555c1aeb0) at gdraw/gdraw.c:789
#28 0x0000555555815b29 in fontforge_main (argc=2, argv=0x7fffffffdd68) at fontforgeexe/startui.c:1415
#29 0x00005555555aab29 in main (argc=2, argv=0x7fffffffdd68) at fontforgeexe/main.c:33
```

Reproduction steps:
1. Open necessary file
1. Switch to CID ShinGoUpr-Ultra-Proportional
1. Encoding&rarr;Compact
1. New Metrics Window
1. Type (very important, **do not paste**) `/numbersign/numbersign/numbersign`
1. Crash!

Alternate stack trace:

```
double free or corruption (out)

Program received signal SIGABRT, Aborted.
0x0000155553958755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553958755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553943851 in abort () at /usr/lib/libc.so.6
#2  0x000015555399aa38 in __libc_message () at /usr/lib/libc.so.6
#3  0x00001555539a125a in  () at /usr/lib/libc.so.6
#4  0x00001555539a2c50 in _int_free () at /usr/lib/libc.so.6
#5  0x0000155553ed7553 in pango_glyph_string_free () at /usr/lib/libpango-1.0.so.0
#6  0x0000155553ecc7cc in  () at /usr/lib/libpango-1.0.so.0
#7  0x0000155553b226a8 in g_slist_foreach () at /usr/lib/libglib-2.0.so.0
#8  0x0000155553ecc776 in pango_layout_line_unref () at /usr/lib/libpango-1.0.so.0
#9  0x0000155553ecc88c in  () at /usr/lib/libpango-1.0.so.0
#10 0x0000155553ece1b5 in pango_layout_set_text () at /usr/lib/libpango-1.0.so.0
#11 0x00005555558c7e0d in GGDKDrawDoText8
    (w=0x555556349680, x=10, y=32, text=0x55556a8819c0 "0 (0x0) U+00A0 \"space\" NO-BREAK SPACE", cnt=-1, col=5869254, drawit=tf_drawit, arg=0x7fffffffc000) at gdraw/ggdkcdraw.c:1254
#12 0x000055555585391d in GDrawDrawText8
    (gw=0x555556349680, x=10, y=32, text=0x55556a8819c0 "0 (0x0) U+00A0 \"space\" NO-BREAK SPACE", cnt=-1, col=5869254) at gdraw/gdrawtxt.c:125
#13 0x0000555555708e59 in FVDrawInfo (fv=0x555555e052f0, pixmap=0x555556349680, event=0x7fffffffc510) at fontforgeexe/fontview.c:6122
#14 0x000055555570c0de in fv_e_h (gw=0x555556349680, event=0x7fffffffc510) at fontforgeexe/fontview.c:6895
#15 0x000055555584b75f in _GWidget_Container_eh (gw=0x555556349680, event=0x7fffffffc510) at gdraw/gcontainer.c:281
#16 0x000055555584d81c in _GWidget_TopLevel_eh (gw=0x555556349680, event=0x7fffffffc510) at gdraw/gcontainer.c:747
#17 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x555556349680, event=0x7fffffffc510, eh=0x55555584ce8e <_GWidget_TopLevel_eh>)
    at gdraw/ggdkdraw.c:329
#18 0x0000555555862f47 in _GGDKDraw_DispatchEvent (event=0x7fffffffc5d0, data=0x555555c1ab30) at gdraw/ggdkdraw.c:1232
#19 0x00001555541bc8b4 in  () at /usr/lib/libgdk-3.so.0
#20 0x00001555541af142 in  () at /usr/lib/libgdk-3.so.0
#21 0x00001555541aeb2f in  () at /usr/lib/libgdk-3.so.0
#22 0x00001555541aecfd in  () at /usr/lib/libgdk-3.so.0
#23 0x0000155553c2bb4a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#24 0x0000155553c2c7f0 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#25 0x00001555541b8ad0 in  () at /usr/lib/libgdk-3.so.0
#26 0x00001555541c735c in  () at /usr/lib/libgdk-3.so.0
#27 0x0000155553b4ca74 in  () at /usr/lib/libglib-2.0.so.0
#28 0x0000155553b4d27f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#29 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
#30 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#31 0x0000555555865c72 in GGDKDrawEventLoop (gdisp=0x555555c1ab30) at gdraw/ggdkdraw.c:2190
#32 0x0000555555851779 in GDrawEventLoop (gdisp=0x555555c1ab30) at gdraw/gdraw.c:789
--Type <RET> for more, q to quit, c to continue without paging--
#33 0x0000555555815b29 in fontforge_main (argc=2, argv=0x7fffffffdd68) at fontforgeexe/startui.c:1415
#34 0x00005555555aab29 in main (argc=2, argv=0x7fffffffdd68) at fontforgeexe/main.c:33
```

**Comment by ctrlcctrlv** [comment]
This CID code is a huge mess. I can't figure out how any of it is supposed to even work. `MapAddEnc` doesn't even check if maps are compact. `SFFindSlot` checks `sf->cidmaster!=NULL && !map->enc->is_compact` (if the font is CID-keyed and not compact), but then doesn't check if the font is CID-keyed AND compact.

I don't think it's fruitful I spend any more time on debugging this. I think we should acknowledge in documentation how buggy this stuff is and recommend people use third-party tools, such as those by Adobe, to turn CID-keyed fonts into normal GID-keyed fonts, before editing with FontForge.

What do you think @frank-trampe ?

**Comment by ctrlcctrlv** [comment]
(Or, even recommend using CID&rarr;Flatten instead of trying to use CID-keyed fonts as they are in FontForge; I consider myself a quite experienced FontForge user and have gotten nothing but crashes from doing it the other way&hellip;)

**Comment by jtanx** [comment]
<details><summary>ASan stacktrace</summary>

```
=================================================================
==14753==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x556d47c5b849 bp 0x7ffc7adb7490 sp 0x7ffc7adb7370 T0)
==14753==The signal is caused by a READ memory access.
==14753==Hint: address points to the zero page.
    #0 0x556d47c5b848 in MVTextChanged ../fontforgeexe/metricsview.c:1947
    #1 0x556d47c5cdbc in MV_TextChanged ../fontforgeexe/metricsview.c:2111
    #2 0x556d47c5cfc4 in MV_TextChanged ../fontforgeexe/metricsview.c:2095
    #3 0x556d47e7a95c in GTextFieldChanged ../gdraw/gtextfield.c:213
    #4 0x556d47e905f6 in gtextfield_key ../gdraw/gtextfield.c:1868
    #5 0x556d47dc292f in _GWidget_TopLevel_Key ../gdraw/gcontainer.c:518
    #6 0x556d47dc7881 in _GWidget_TopLevel_eh ../gdraw/gcontainer.c:673
    #7 0x556d47deec4e in _GGDKDraw_CallEHChecked ../gdraw/ggdkdraw.c:346
    #8 0x556d47df0c84 in _GGDKDraw_DispatchEvent ../gdraw/ggdkdraw.c:1249
    #9 0x7f57cb825764  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x37764)
    #10 0x7f57cb855f91  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x67f91)
    #11 0x7f57cab58416 in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c416)
    #12 0x7f57cab5864f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c64f)
    #13 0x7f57cab586db in g_main_context_iteration (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c6db)
    #14 0x556d47debb2c in GGDKDrawEventLoop ../gdraw/ggdkdraw.c:2216
    #15 0x556d47d61e6d in fontforge_main ../fontforgeexe/startui.c:1414
    #16 0x7f57ca73cb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #17 0x556d47904bf9 in _start (/home/jeremy/ffstaging/build/bin/fontforge+0x160bf9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../fontforgeexe/metricsview.c:1947 in MVTextChanged
```
</details>

**Comment by jtanx** [comment]
I guess somewhat related to #1661. 

If I understand correctly, cid-keyed fonts already use the custom encoding under the hood. When compacting is turned on, it also uses the custom encoding. While there's that `is_compact` flag, it's actually useless, as it's never set to true - a side-effect of                            
c0c60e7f669525f38ef34a5466bfca94766f39fe which removed the `compact` encoding.

So what's happening here is that it `is_compact` is false even though it should be true, and then everything blows up. No real easy fix that I can see, maybe #1661 should be addressed first.
