### ISSUE TITLE
Crash when uncompacting encoding

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#3947]
Before I write any more, I just want to say, _I'm sorry if you're getting all these emails when I'm filing bugs. I'm not trying to spam anyone. If I don't file these issues, I'll forget how I caused crashes/corruption. I am not trying to file more than one issue for the same bug, I try to make sure the tracebacks and reproduction steps are very different; although with this one it might turn out that whatever fixes #3946 will fix this, I'm not sure of that._

Necessary file: [A-OTF-PreMomoStd-Bold.otf](https://github.com/fontforge/fontforge/files/3638492/A-OTF-PreMomoStd-Bold.zip)

1. Open necessary file
1. Switch CID to PreMomoStd-Bold-Proportional
1. Encoding&rarr;Compact
1. New Metrics Window
1. Type &laquo;Morisawa eee&raquo; (w/o _guillemets_, the space is **very** important)
1. Note similar corruption as #3946, except this time *no spaces* are appearing for some reason
1. Back in FontView, uncompact the encoding
1. Crash!

```
in:0x5555560d3a40 end:0x5555560d3a70 got char 77 M
in:0x5555560d3a44 end:0x5555560d3a70 got char 111 o
in:0x5555560d3a48 end:0x5555560d3a70 got char 114 r
in:0x5555560d3a4c end:0x5555560d3a70 got char 105 i
in:0x5555560d3a50 end:0x5555560d3a70 got char 115 s
in:0x5555560d3a54 end:0x5555560d3a70 got char 97 a
in:0x5555560d3a58 end:0x5555560d3a70 got char 119 w
in:0x5555560d3a5c end:0x5555560d3a70 got char 97 a
in:0x5555560d3a60 end:0x5555560d3a70 got char 32  
in:0x5555560d3a64 end:0x5555560d3a70 got char 101 e
in:0x5555560d3a68 end:0x5555560d3a70 got char 101 e
in:0x5555560d3a6c end:0x5555560d3a70 got char 101 e
double free or corruption (out)

Program received signal SIGABRT, Aborted.
0x0000155553958755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x0000155553958755 in raise () at /usr/lib/libc.so.6
#1  0x0000155553943851 in abort () at /usr/lib/libc.so.6
#2  0x000015555399aa38 in __libc_message () at /usr/lib/libc.so.6
#3  0x00001555539a125a in  () at /usr/lib/libc.so.6
#4  0x00001555539a2c50 in _int_free () at /usr/lib/libc.so.6
#5  0x00001555550e84e4 in EncMapFree (map=0x555555eb1fb0) at fontforge/splineutil.c:6309
#6  0x0000155554e8bc0a in FVCompact (fv=0x555555eb1e30) at fontforge/fontviewbase.c:1527
#7  0x0000555555703658 in FVMenuCompact (gw=0x555556106480, UNUSED_mi=0x5555560bdca0, UNUSED_e=0x7fffffffcc60)
    at fontforgeexe/fontview.c:4803
#8  0x000055555587ec0a in gmenu_mouse (m=0x555555f76ec0, event=0x7fffffffcc60) at gdraw/gmenu.c:948
#9  0x00005555558806cd in gmenu_eh (w=0x555555f76fd0, ge=0x7fffffffcc60) at gdraw/gmenu.c:1389
#10 0x0000555555860524 in _GGDKDraw_CallEHChecked (gw=0x555555f76fd0, event=0x7fffffffcc60, eh=
    0x5555558805f4 <gmenu_eh>) at gdraw/ggdkdraw.c:329
#11 0x0000555555862f47 in _GGDKDraw_DispatchEvent (event=0x555555bfd1f0, data=0x555555c17dd0)
    at gdraw/ggdkdraw.c:1232
#12 0x00001555541bc8b4 in  () at /usr/lib/libgdk-3.so.0
#13 0x0000155554169904 in  () at /usr/lib/libgdk-3.so.0
#14 0x0000155553b4d3ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x0000155553b4f1c1 in  () at /usr/lib/libglib-2.0.so.0
#16 0x0000155553b4f201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x0000555555865c72 in GGDKDrawEventLoop (gdisp=0x555555c17dd0) at gdraw/ggdkdraw.c:2190
#18 0x0000555555851779 in GDrawEventLoop (gdisp=0x555555c17dd0) at gdraw/gdraw.c:789
#19 0x0000555555815b29 in fontforge_main (argc=2, argv=0x7fffffffe098) at fontforgeexe/startui.c:1415
#20 0x00005555555aab29 in main (argc=2, argv=0x7fffffffe098) at fontforgeexe/main.c:33
```

**Comment by jtanx** [comment]
<details><summary>Asan stacktrace</summary>

```
=================================================================
==9709==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c000007878 at pc 0x7fe6ea0d890c bp 0x7ffc7fe12e50 sp 0x7ffc7fe12e40
WRITE of size 8 at 0x61c000007878 thread T0
    #0 0x7fe6ea0d890b in SFAddGlyphAndEncode ../fontforge/encoding.c:2439
    #1 0x7fe6ea150c58 in SFGetOrMakeChar ../fontforge/fvfonts.c:923
    #2 0x5651043927cd in WordlistEscapedInputStringToParsedDataComplex ../fontforgeexe/wordlistparser.c:524
    #3 0x56510425d59a in MVTextChanged ../fontforgeexe/metricsview.c:1930
    #4 0x56510425edbc in MV_TextChanged ../fontforgeexe/metricsview.c:2111
    #5 0x56510425efc4 in MV_TextChanged ../fontforgeexe/metricsview.c:2095
    #6 0x56510447c95c in GTextFieldChanged ../gdraw/gtextfield.c:213
    #7 0x5651044925f6 in gtextfield_key ../gdraw/gtextfield.c:1868
    #8 0x5651043c492f in _GWidget_TopLevel_Key ../gdraw/gcontainer.c:518
    #9 0x5651043c9881 in _GWidget_TopLevel_eh ../gdraw/gcontainer.c:673
    #10 0x5651043f0c4e in _GGDKDraw_CallEHChecked ../gdraw/ggdkdraw.c:346
    #11 0x5651043f2c84 in _GGDKDraw_DispatchEvent ../gdraw/ggdkdraw.c:1249
    #12 0x7fe6e8fcd764  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x37764)
    #13 0x7fe6e8ffdf91  (/usr/lib/x86_64-linux-gnu/libgdk-3.so.0+0x67f91)
    #14 0x7fe6e8300416 in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c416)
    #15 0x7fe6e830064f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c64f)
    #16 0x7fe6e83006db in g_main_context_iteration (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c6db)
    #17 0x5651043edb2c in GGDKDrawEventLoop ../gdraw/ggdkdraw.c:2216
    #18 0x565104363e6d in fontforge_main ../fontforgeexe/startui.c:1414
    #19 0x7fe6e7ee4b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #20 0x565103f06bf9 in _start (/home/jeremy/ffstaging/build/bin/fontforge+0x160bf9)

0x61c000007878 is located 8 bytes to the left of 1848-byte region [0x61c000007880,0x61c000007fb8)
allocated by thread T0 here:
    #0 0x7fe6eb092d38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fe6ea253bdd in cidfigure ../fontforge/parsettf.c:3884
    #2 0x7fe6ea253bdd in readcffglyphs ../fontforge/parsettf.c:4001
    #3 0x7fe6ea263d30 in readttf ../fontforge/parsettf.c:5593
    #4 0x7fe6ea263d30 in _SFReadTTF ../fontforge/parsettf.c:6336
    #5 0x7fe6ea4c2560 in _ReadSplineFont ../fontforge/splinefont.c:1142
    #6 0x7fe6ea4c3f4c in LoadSplineFont ../fontforge/splinefont.c:1380
    #7 0x7fe6ea12671f in ViewPostScriptFont ../fontforge/fontviewbase.c:1348
    #8 0x565104363e0a in fontforge_main ../fontforgeexe/startui.c:1390
    #9 0x7fe6e7ee4b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../fontforge/encoding.c:2439 in SFAddGlyphAndEncode
Shadow bytes around the buggy address:
  0x0c387fff8eb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8ec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8ed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8ee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8ef0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c387fff8f00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c387fff8f10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c387fff8f50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==9709==ABORTING
```

</details>
