### ISSUE TITLE
ffpython import fontforge & psMat modules error on Windows

### ISSUE THREAD

**Issue by snoopy-coder** [fontforge/fontforge#3981]
I'm trying to install `fontforge` and `psMat` modules, but I'm having trouble with this error:
```
Python 3.7.4 (default, Jul 30 2019, 07:47:48)  [GCC 9.1.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fontforge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
>>> import psMat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```
I checked this problem on two releases - Aug 1,2019 (Python 3.7.4) & Apr 13, 2019 (Python 2.7.16) - the result is absolutely the same. Thanks in advance for any help you might offer as I am helpless.

**Comment by jtanx** [comment]
What's your Windows version?

**Comment by snoopy-coder** [comment]
Windows 7 SP1 x64 (6.1.7601)

**Comment by jtanx** [comment]
If you go to `C:\Program Files (x86)\FontForgeBuilds\bin` in Windows Explorer and double click on ffpython.exe, what happens? It should launch the python console. If it doesn't it should tell you what dll is missing.

**Comment by snoopy-coder** [comment]
I run `fontforge-console.bat` from `C:\Program Files (x86)\FontForgeBuilds` and then I run `ffpython.exe` manually:

 ![](https://thumbs2.imgbox.com/f8/d6/cpVXcv5v_t.jpg)
[Enlarge](http://imgbox.com/cpVXcv5v)

I suspect that violated any dependencies `fontforge.pyd` and `psMat.pyd` from `C:\Program Files (x86)\FontForgeBuilds\lib\python3.7\site-packages`

**Comment by jtanx** [comment]
There's a couple of things you can try:

1. If you run `ffpython -v`, what do you see when you import the module? This is what I see on Windows 7:  
![image](https://user-images.githubusercontent.com/5137410/67152572-c15d4c00-f324-11e9-8bdc-6b7e0cc22beb.png)
2. Get [dependency walker](http://www.dependencywalker.com/), copy `fontforge.pyd` into the `bin` folder, and open that `fontforge.pyd` in the dependency walker. See what dll is missing

**Comment by snoopy-coder** [comment]
Unfortunately, I could not find anything definite, except verbose log (ffpython.exe -v):
```
Python 3.7.4 (default, Jul 30 2019, 07:47:48)  [GCC 9.1.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>> import fontforge
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified procedure could not be found.
>>> import psMat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified procedure could not be found.
>>>
```
And outdated FontForge [discussion thread](https://sourceforge.net/p/fontforge/mailman/message/36038796/) on sourceforge.net describing a similar problem.

**Comment by snoopy-coder** [comment]
Through trial and error I finally found the [solution here.](https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows/1711338#1711338)

**Comment by kiwi0fruit** [comment]
It's still not fixed? I uninstalled FontForge-2019-08-01-Windows.exe and installed FontForge-2019-03-17-Windows.exe -- bug is gone.

**Comment by ctrlcctrlv** [comment]
I'll reopen this bug for you; I agree with you that it's still an issue and installing third party stuff as @snoopy-coder did is not an acceptable solution long term for the project.
