### ISSUE TITLE
Easily reproducible freeze in SplineSetStroke

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4054]
# Settings

![2019-12-11-134805_1088x1145_scrot](https://user-images.githubusercontent.com/838783/70594993-129b0500-1c1d-11ea-9470-50c6851e839f.png)

# File

[m.sfd](https://github.com/fontforge/fontforge/files/3948652/m.zip)

# Representative backtrace

```gdb
(gdb) bt
#0  0x00001555550ff3a6 in ForceEndPointExtrema (s=0x555555ef18c0, isto=1) at ../fontforge/splineutil2.c:2598
#1  0x0000155555100891 in SplineAddExtrema
    (s=0x555555ef18c0, always=1, lenbound=0, offsetbound=0, b=0x7ffffffc2840)
    at ../fontforge/splineutil2.c:2783
#2  0x0000155555100e1d in SplineSetAddExtrema
    (sc=0x0, ss=0x555555eedd50, between_selected=ae_all, emsize=1000) at ../fontforge/splineutil2.c:2875
#3  0x0000155555100f5c in SplineCharAddExtrema
    (sc=0x0, head=0x555555eeb130, between_selected=ae_all, emsize=1000) at ../fontforge/splineutil2.c:2901
#4  0x00001555550cb833 in SplineSetStroke (ss=0x555555dcbef0, si=0x555555e40570, order2=1)
    at ../fontforge/splinestroke.c:2038
#5  0x00001555550cbc13 in FVStrokeItScript
    (_fv=0x555555dd7ae0, si=0x555555e40570, UNUSED_pointless_argument=0) at ../fontforge/splinestroke.c:2078
#6  0x000055555568eed8 in _Stroke_OK (sd=0x7ffffffc5a50, isapply=0) at ../fontforgeexe/cvstroke.c:238
#7  0x000055555568ef87 in Stroke_OK (g=0x555555e79ab0, e=0x7ffffffc2c80) at ../fontforgeexe/cvstroke.c:248
#8  0x00005555558426b3 in GButtonInvoked (b=0x555555e79ab0, ev=0x7ffffffc2fa0) at ../gdraw/gbuttons.c:257
#9  0x000055555584362a in gbutton_mouse (g=0x555555e79ab0, event=0x7ffffffc2fa0) at ../gdraw/gbuttons.c:485
#10 0x000055555584dce8 in _GWidget_Container_eh (gw=0x555555e4e660, event=0x7ffffffc2fa0)
    at ../gdraw/gcontainer.c:304
#11 0x000055555584fb68 in _GWidget_TopLevel_eh (gw=0x555555e4e660, event=0x7ffffffc2fa0)
    at ../gdraw/gcontainer.c:747
#12 0x0000555555862888 in _GGDKDraw_CallEHChecked (gw=0x555555e4e660, event=0x7ffffffc2fa0, eh=
    0x55555584f1da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#13 0x00005555558652ab in _GGDKDraw_DispatchEvent (event=0x555555ed2ac0, data=0x555555be5af0)
    at ../gdraw/ggdkdraw.c:1237
#14 0x0000155554195954 in  () at /usr/lib/libgdk-3.so.0
#15 0x0000155554142904 in  () at /usr/lib/libgdk-3.so.0
#16 0x0000155553d1639e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#17 0x0000155553d181b1 in  () at /usr/lib/libglib-2.0.so.0
#18 0x0000155553d181f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#19 0x0000555555867fd9 in GGDKDrawProcessOneEvent (gdisp=0x555555be5af0) at ../gdraw/ggdkdraw.c:2193
#20 0x0000555555853a00 in GDrawProcessOneEvent (gdisp=0x555555be5af0) at ../gdraw/gdraw.c:764
#21 0x0000555555696291 in MakeStrokeDlg (cv=0x555555dd7ae0, strokeit=
    0x1555550cb8be <FVStrokeItScript>, si=0x555555e40570, apply=0) at ../fontforgeexe/cvstroke.c:1179
#22 0x0000555555696464 in FVStroke (fv=0x555555dd7ae0) at ../fontforgeexe/cvstroke.c:1211
#23 0x00005555556fe750 in FVMenuStroke (gw=0x555555de9e80, UNUSED_mi=0x555555dfd2b0, UNUSED_e=0x0)
    at ../fontforgeexe/fontview.c:2616
#24 0x000055555588432c in GMenuBarCheckHotkey (top=0x555555de9e80, g=0x555555dea7f0, event=0x7fffffffd0a0)
    at ../gdraw/gmenu.c:1966
#25 0x000055555588455a in GMenuBarCheckKey (top=0x555555de9e80, g=0x555555dea7f0, event=0x7fffffffd0a0)
    at ../gdraw/gmenu.c:2015
#26 0x000055555584ebae in _GWidget_TopLevel_Key
    (top=0x555555de9e80, ew=0x555555de9e80, event=0x7fffffffd0a0) at ../gdraw/gcontainer.c:507
#27 0x000055555584f68b in _GWidget_TopLevel_eh (gw=0x555555de9e80, event=0x7fffffffd0a0)
    at ../gdraw/gcontainer.c:682
#28 0x0000555555862888 in _GGDKDraw_CallEHChecked (gw=0x555555de9e80, event=0x7fffffffd0a0, eh=
    0x55555584f1da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#29 0x00005555558652ab in _GGDKDraw_DispatchEvent (event=0x555555bcabd0, data=0x555555be5af0)
    at ../gdraw/ggdkdraw.c:1237
#30 0x0000155554195954 in  () at /usr/lib/libgdk-3.so.0
#31 0x0000155554142904 in  () at /usr/lib/libgdk-3.so.0
#32 0x0000155553d1639e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#33 0x0000155553d181b1 in  () at /usr/lib/libglib-2.0.so.0
#34 0x0000155553d181f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#35 0x0000555555868055 in GGDKDrawEventLoop (gdisp=0x555555be5af0) at ../gdraw/ggdkdraw.c:2204
#36 0x0000555555853add in GDrawEventLoop (gdisp=0x555555be5af0) at ../gdraw/gdraw.c:784
#37 0x0000555555817d70 in fontforge_main (argc=2, argv=0x7fffffffe4d8) at ../fontforgeexe/startui.c:1415
#38 0x00005555555aab89 in main (argc=2, argv=0x7fffffffe4d8) at ../fontforgeexe/main.c:33
```

**Comment by skef** [comment]
Clearly this is another Add Extrema bug to track down.

**Comment by skef** [comment]
Hmm. This one isn't reproducing for me either. (Note that I did notice the RO -> None setting and that doesn't change the result for me.) 

These Extrema bugs are very sensitive to fine values and can sometimes be eliminated by the saving process alone. Did you construct the spline and run the stroke code without saving in between? If so that could account for the discrepancy.

**Comment by ctrlcctrlv** [comment]
It does reproduce from a saved file for me, yes. If it is so sensitive, we are both running on 64-bit systems, right?

**Comment by skef** [comment]
I'll try again with this one too. Maybe I just screwed up my source tracking.

**Comment by skef** [comment]
No, definitely compiled with previous-to-4052-fix master and can't seem to trigger this one. 
 
And yes my system is 64 bits.

**Comment by ctrlcctrlv** [comment]
This was fixed by #4052, so I'm not sure it matters why you couldn't repro it.

**Comment by skef** [comment]
Actually for this one we should reopen and work a bit more at trying to get it to reproduce for me. #4055 may have *avoided* this, but it's a non-terminating loop caused by a certain geometry. Nothing should be able to cause a non-terminating loop.

**Comment by ctrlcctrlv** [comment]
If you want to hop on IRC, I'm happy to run any gdb command like we did last time for that GSUB table issue.

**Comment by skef** [comment]
On there now
