### ISSUE TITLE
GFileChooser segmentation fault when going to directory with certain filenames

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4159]
Caught while looking into https://github.com/fontforge/fontforge/issues/2475#issuecomment-583849612

This is a tracking issue, I plan to fix this today

Steps to reproduce:

1. Extract [fonts-richstyle_0.4.tar](https://richstyle.org/downloads/src/fonts-richstyle_0.4.tar) to `/tmp`
2. New font, any glyph
3. Go to directory `/tmp/fonts-richstyle_0.4/SVGs/`
4. Make sure type is SVG&hellip;
5. Crash!

Note: This crash only happens if `LC_ALL` is a UTF-8 one, like `en_US.UTF-8`

```
(gdb) bt
#0  0x0000155553b2114c in strcoll_l () at /usr/lib/libc.so.6
#1  0x00005555558c2bf0 in GTextInfoCompare (ti1=0x555555e267b0, ti2=0x555555e267f0) at ../gdraw/gtextinfo.c:718
#2  0x000055555586ead3 in GListAlphaCompare (v1=0x555555e25eb0, v2=0x555555e25eb8) at ../gdraw/glist.c:124
#3  0x0000155553acc605 in msort_with_tmp.part () at /usr/lib/libc.so.6
#4  0x0000155553acc592 in msort_with_tmp.part () at /usr/lib/libc.so.6
#5  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#6  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#7  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#8  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#9  0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#10 0x0000155553acc575 in msort_with_tmp.part () at /usr/lib/libc.so.6
#11 0x0000155553acc936 in qsort_r () at /usr/lib/libc.so.6
#12 0x000055555586eb15 in GListOrderIt (gl=0x555555dff190) at ../gdraw/glist.c:128
#13 0x000055555586fe4a in GListSetList (g=0x555555dff190, ti=0x555555e25ea0, docopy=0) at ../gdraw/glist.c:425
#14 0x00005555558623c9 in GGadgetSetList (g=0x555555dff190, ti=0x555555e25ea0, copyit=0) at ../gdraw/ggadgets.c:1291
#15 0x00005555558584bb in GFileChooserFillList (gfc=0x555555c8a2c0, first=0x555555db3050, dir=0x555555e364f0) at ../gdraw/gfilechooser.c:367
#16 0x0000555555858609 in GFileChooserReceiveDir (gc=0x555555e250f0) at ../gdraw/gfilechooser.c:389
#17 0x0000155554e0357a in _gio_file_dir (gc=0x555555e250f0, path=0x555555e11d80 "/tmp/fonts-richstyle_0.4/SVGs/") at ../gutils/giofile.c:182
#18 0x0000155554e03a10 in _GIO_localDispatch (gc=0x555555e250f0) at ../gutils/giofile.c:254
#19 0x0000155554e02bc9 in GIOdispatch (gc=0x555555e250f0, gf=gf_dir) at ../gutils/gio.c:144
#20 0x0000155554e02c51 in GIOdir (gc=0x555555e250f0) at ../gutils/gio.c:161
#21 0x0000555555858c8a in GFileChooserScanDir (gfc=0x555555c8a2c0, dir=0x555555dd9b60) at ../gdraw/gfilechooser.c:479
#22 0x000055555585bfca in GFileChooserRefreshList (g=0x555555c8a2c0) at ../gdraw/gfilechooser.c:1342
#23 0x0000555555665b85 in GFD_Format (g=0x555555e122e0, e=0x7fffffffbcc0) at ../fontforgeexe/cvimportdlg.c:541
#24 0x0000555555846a38 in GListButtonSelected (g=0x555555e122e0, i=3) at ../gdraw/gbuttons.c:1149
#25 0x000055555587253e in popup_eh (popup=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/glist.c:1074
#26 0x000055555584f8a7 in _GWidget_Container_eh (gw=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/gcontainer.c:405
#27 0x0000555555850e68 in _GWidget_TopLevel_eh (gw=0x555555e176e0, event=0x7fffffffbfb0) at ../gdraw/gcontainer.c:747
#28 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e176e0, event=0x7fffffffbfb0, eh=0x5555558504da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#29 0x000055555586945e in GGDKDrawPostEvent (e=0x7fffffffbfb0) at ../gdraw/ggdkdraw.c:2224
#30 0x0000555555854e2c in GDrawPostEvent (e=0x7fffffffbfb0) at ../gdraw/gdraw.c:791
#31 0x000055555586e78c in GListSelected (l=0x555555e09f40, frommouse=1, index=3) at ../gdraw/glist.c:51
#32 0x0000555555870bfc in glist_mouse (g=0x555555e09f40, event=0x7fffffffc2d0) at ../gdraw/glist.c:599
#33 0x000055555584efe8 in _GWidget_Container_eh (gw=0x555555e176e0, event=0x7fffffffc2d0) at ../gdraw/gcontainer.c:304
#34 0x0000555555850e68 in _GWidget_TopLevel_eh (gw=0x555555e176e0, event=0x7fffffffc2d0) at ../gdraw/gcontainer.c:747
#35 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e176e0, event=0x7fffffffc2d0, eh=0x5555558504da <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:334
#36 0x00005555558665ab in _GGDKDraw_DispatchEvent (event=0x555555bbb510, data=0x555555bd56c0) at ../gdraw/ggdkdraw.c:1237
#37 0x0000155554140954 in  () at /usr/lib/libgdk-3.so.0
#38 0x00001555540ed904 in  () at /usr/lib/libgdk-3.so.0
#39 0x0000155553cc139e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#40 0x0000155553cc31b1 in  () at /usr/lib/libglib-2.0.so.0
#41 0x0000155553cc31f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#42 0x00005555558692d9 in GGDKDrawProcessOneEvent (gdisp=0x555555bd56c0) at ../gdraw/ggdkdraw.c:2193
#43 0x0000555555854d00 in GDrawProcessOneEvent (gdisp=0x555555bd56c0) at ../gdraw/gdraw.c:764
#44 0x0000555555666de2 in _Import (cv=0x15554f1e7010, bv=0x0, fv=0x0) at ../fontforgeexe/cvimportdlg.c:783
#45 0x0000555555666e3c in CVImport (cv=0x15554f1e7010) at ../fontforgeexe/cvimportdlg.c:788
#46 0x0000555555608f6d in CVMenuImport (gw=0x555555da2a90, UNUSED_mi=0x555555da4fe0, UNUSED_e=0x7fffffffcff0) at ../fontforgeexe/charview.c:6775
#47 0x00005555558822ed in gmenu_mouse (m=0x555555ba8660, event=0x7fffffffcff0) at ../gdraw/gmenu.c:948
#48 0x0000555555883db0 in gmenu_eh (w=0x555555e0ee60, ge=0x7fffffffcff0) at ../gdraw/gmenu.c:1389
#49 0x0000555555863b88 in _GGDKDraw_CallEHChecked (gw=0x555555e0ee60, event=0x7fffffffcff0, eh=0x555555883cd7 <gmenu_eh>) at ../gdraw/ggdkdraw.c:334
#50 0x00005555558665ab in _GGDKDraw_DispatchEvent (event=0x555555dee8e0, data=0x555555bd56c0) at ../gdraw/ggdkdraw.c:1237
#51 0x0000155554140954 in  () at /usr/lib/libgdk-3.so.0
#52 0x00001555540ed904 in  () at /usr/lib/libgdk-3.so.0
#53 0x0000155553cc139e in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#54 0x0000155553cc31b1 in  () at /usr/lib/libglib-2.0.so.0
#55 0x0000155553cc31f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#56 0x0000555555869355 in GGDKDrawEventLoop (gdisp=0x555555bd56c0) at ../gdraw/ggdkdraw.c:2204
#57 0x0000555555854ddd in GDrawEventLoop (gdisp=0x555555bd56c0) at ../gdraw/gdraw.c:784
#58 0x0000555555819001 in fontforge_main (argc=2, argv=0x7fffffffe438) at ../fontforgeexe/startui.c:1415
#59 0x00005555555aab89 in main (argc=2, argv=0x7fffffffe438) at ../fontforgeexe/main.c:33
```

The problem is a comparison at frame 2:

```
(gdb) frame
#2  0x000055555586ead3 in GListAlphaCompare (v1=0x555555e25eb0, v2=0x555555e25eb8) at ../gdraw/glist.c:124
124	return( GTextInfoCompare(*pt1,*pt2));
(gdb) wc ((**pt1).text)
"[d83d][dec0].svg"
(gdb) wc ((**pt2).text)
"[e001].svg"
```

This calls, at frame 1, `strcoll`, which relies on the return value of `u2utf8_copy`, which in turn relies on `utf8_ipdb`, which returns an error if any PUA character is detected! That's simply the wrong thing to do, and I don't know why George thought otherwise.

**Comment by ctrlcctrlv** [comment]
Update: The problem are the surrogate pairs, actually. U+D83D, U+DEC0, those are not PUA codepoints, silly me.

I don't know if it's valid to encode surrogate pairs in UTF-8. Maybe? We shouldn't crash if we find some, though. But George isn't the problem here.
