### ISSUE TITLE
Test failures on ppc64

### ISSUE THREAD

**Issue by floppym** [fontforge/fontforge#4295]
On Gentoo Linux, we get a few test failures on ppc64 with fontforge-20200314. Please advise on any additional information you need to diagnose the issue.
```
The following tests FAILED:
	54 - test0004_py (Failed)
	55 - test0004_pyhook (Failed)
	80 - test1009_py (Failed)
	81 - test1009_pyhook (Failed)
```
[LastTest.log](https://github.com/fontforge/fontforge/files/4530100/LastTest.log)

Gentoo bug: https://bugs.gentoo.org/719058

CC: @asarubbo

**Comment by jtanx** [comment]
Is there an easily accessible VM to test on? Might be a bit hard to debug this without.


```
Test /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test0004.py(mode=pyhook): OpenType script tag tests
Running: /usr/bin/python3.6 -Ss /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test0004.py
Traceback (most recent call last):
  File "/var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test0004.py", line 5, in <module>
    assert fontforge.scriptFromUnicode(ord('ᜈ')) == "tagl"
AssertionError
Test /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test0004.py failed with exit code 1
<end of output>
Test time =   0.07 sec
```

```
Test /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test1009.py(mode=py): Ligatures and Fractions Table Lookups
Running: /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314_build/bin/fontforge -lang py -script /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test1009.py
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20200314
 Based on sources from 2020-04-24 10:18 UTC-ML-D.
Get Table Array Totals.
Test valid (and invalid) ligatures.
PythonUI_Init()
copyUIMethodsToBaseTable()
Traceback (most recent call last):
  File "/var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test1009.py", line 23, in <module>
    raise ValueError("Expected Ligature table array 'n' values of 0,1,3,7,-1.")
ValueError: Expected Ligature table array 'n' values of 0,1,3,7,-1.
Test /var/tmp/portage/media-gfx/fontforge-20200314/work/fontforge-20200314/tests/test1009.py failed with exit code 1
<end of output>
Test time =   0.52 sec
```

**Comment by jtanx** [comment]
Is this big endian?

**Comment by floppym** [comment]
> Is there an easily accessible VM to test on? Might be a bit hard to debug this without.

I'll see if we can get you access.

> Is this big endian?

Yes.

**Comment by mjeveritt** [comment]
Going back through older versions, I can replicate two (one+python) failures with 20190801.

See https://bugs.gentoo.org/719058#c6 and #c7 for further details.

**Comment by jtanx** [comment]
I managed to get a workable test environment with a debian ppc64 chroot. Hopefully #4297 will fix the failing tests, we'll see in an hour or two when my changes finally recompile...

**Comment by floppym** [comment]
Thanks for looking into it, and sorry we couldn't get you a test environment sooner.

**Comment by jtanx** [comment]
No worries, if there were any other bugs I'd probably take up your offer :)
