### ISSUE TITLE
Crash when generating with data on a non-foreground layer

### ISSUE THREAD

**Issue by jtanx** [fontforge/fontforge#4314]
* Create a new font
* Add a point to the background layer
* Try to generate a font

```
Program received signal SIGSEGV, Segmentation fault.
DoSave (d=0x7fffffff7d80, path=0x555555e766a0)
    at ../fontforgeexe/savefontdlg.c:1349
1349            layer = (intpt) GGadgetGetListItemSelected(GWidgetGetControl(d->gw,CID_Layers))->userdata;
(gdb) bt
#0  DoSave (d=0x7fffffff7d80, path=0x555555e766a0)
    at ../fontforgeexe/savefontdlg.c:1349
#1  0x00005555557d2e16 in GFD_exists (gio=0x555555e74d10)
    at ../fontforgeexe/savefontdlg.c:1611
#2  0x00007ffff78a9400 in _gio_file_statfile
    (gc=0x555555e74d10, path=0x555555eca670 "/home/jeremy/fontforge/build/Untitled1.ttf") at ../gutils/giofile.c:204
#3  0x00007ffff78a9637 in _GIO_localDispatch (gc=0x555555e74d10)
    at ../gutils/giofile.c:257

(gdb) p GWidgetGetControl(d->gw, 402)
$1 = (GGadget *) 0x555555d8fa50
(gdb) p GGadgetGetListItemSelected(GWidgetGetControl(d->gw, 402))
$2 = (GTextInfo *) 0x0

```

**Comment by skef** [comment]
Either I don't quite understand the instructions or this isn't reproducing for me on Arch Linux.
