### ISSUE TITLE
Endless corrupted file, crash on opening

### ISSUE THREAD

**Issue by yg8ijvjvjv** [fontforge/fontforge#4524]
Permacrash of file. Pasted bitmap references. Crash of FontForge

This file download is limited so be sure to test it out before it expires.
https://ufile.io/1q9cmx14

**Comment by yg8ijvjvjv** [comment]
Opening progress quickly fills up to half the progress which is followed by a crash.

**Comment by jtanx** [comment]
```
==============================================================
==5294==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d000053d08                                                                                         at pc 0x7f040795b2bc bp 0x7ffe77c7cd00 sp 0x7ffe77c7ccf0
READ of size 8 at 0x61d000053d08 thread T0
    #0 0x7f040795b2bb in SFDFixupBitmapRefs ../fontforge/sfd.c:6179
    #1 0x7f040795c14c in SFDGetBitmapFont ../fontforge/sfd.c:6282
    #2 0x7f04079780f1 in SFD_GetFont ../fontforge/sfd.c:9005
    #3 0x7f0407978e1e in SFD_Read ../fontforge/sfd.c:9088
    #4 0x7f0407979385 in _SFDRead ../fontforge/sfd.c:9121
    #5 0x7f04079e984a in _ReadSplineFont ../fontforge/splinefont.c:1179
    #6 0x7f04079eb17a in ReadSplineFont ../fontforge/splinefont.c:1322
    #7 0x7f04079eb62b in LoadSplineFont ../fontforge/splinefont.c:1380
    #8 0x7f04074f5f9b in ViewPostScriptFont ../fontforge/fontviewbase.c:1348
    #9 0x5557f18630e2 in fontforge_main ../fontforgeexe/startui.c:1401
    #10 0x5557f11cd3f9 in main ../fontforgeexe/main.c:33
    #11 0x7f0405249bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2                                                                                        1bf6)
    #12 0x5557f11cd2f9 in _start (/home/jeremy/ffstaging/build/bin/fontforge+0x1                                                                                        5c2f9)

Address 0x61d000053d08 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow ../fontforge/sfd.c:6179 in SFDFi                                                                                        xupBitmapRefs
Shadow bytes around the buggy address:
  0x0c3a80002750: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80002760: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80002770: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80002780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80002790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3a800027a0: fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800027b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800027c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800027d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800027e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800027f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5294==ABORTING
```

![image](https://user-images.githubusercontent.com/5137410/101756667-5b381780-3b2a-11eb-91e0-b15e05a8cfb8.png)

The SFD has bitmap references to nonexistent glyphs. How did you generate this sfd?

**Comment by skef** [comment]
@jtanx Could be wrong but I read the description as indicating that this was generated by the autosave system. (Pasted a bitmap reference, FontForge crashed. Tried to open the auto-save and it consistently crashed.)

Either way it does seem that this is a condition FontForge should be able to protect itself from when opening an SFD, especially given that the file is a text format rather than binary. We probably just need to investigate a bit earlier in the open code.

**Comment by yg8ijvjvjv** [comment]
It's made by a glitching where copying bitmap references to another font makes a cross-font reference. When such a font is saved, the references become local font references, and if the references are to nonexistent glyphs in the font, Revert File will initiate a crash.
