### ISSUE TITLE
Library not loaded on python, Image not found

### ISSUE THREAD

**Issue by heismauri** [fontforge/fontforge#4694]
Hello there, I've been reading for the past hour if my problem has been asked before, seems like it has been but my problem seems to be a little different. Every time I try to use fontforge on my python file it gives me this error:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import fontforge
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fontforge.so, 2): Library not loaded: /usr/local/Cellar/glib/2.66.7/lib/libglib-2.0.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/libgio-2.0.0.dylib
  Reason: image not found
```
The thing is that the file already exists but in a different version folder (this is a Mac btw), the file exists in this route `/usr/local/Cellar/glib/2.68.0/lib/libglib-2.0.0.dylib`

So I tried renaming the folder to 2.66.7, sadly, I get a new error:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import fontforge
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fontforge.so, 2): Library not loaded: /usr/local/opt/glib/lib/libglib-2.0.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/libfontforge.4.dylib
  Reason: image not found
```
And I don't know what to do now. Can somebody please help me?

**Comment by jtanx** [comment]
Is this fontforge installed from homebrew or from our app bundle?

**Comment by heismauri** [comment]
> Is this fontforge installed from homebrew or from our app bundle?

I tried both ways and either way I did not have the files. If I run it with the Python available on the Contents folders I do have the fontforge package but not any other packages of my Python installation since it is somehow running a different Python
