### ISSUE TITLE
MetricsView crash in Noto Sans CJK JP: `*mv->chars` is `NULL`

### ISSUE THREAD

**Issue by ctrlcctrlv** [fontforge/fontforge#4706]
Arch Linux, e873b8f43e35bfc8d2053534c4e071a956115819

* ```bash
    gdb /opt/bin/fontforge -ex 'run /usr/share/fonts/noto-cjk/NotoSansCJK-Black.ttc'`
    ```
* Choose Noto Sans CJK JP when prompted
* Give up on CID map
* Choose any letter (e.g. `Identity.1508`, U+3071, ぱ)
* <kbd>Ctrl+K</kbd>
* ![image](https://user-images.githubusercontent.com/838783/114862940-203a3f00-9dbd-11eb-8a11-3544ca01d048.png)
* press space
* MetricsView blanks: ![image](https://user-images.githubusercontent.com/838783/114862993-2e885b00-9dbd-11eb-8c47-19d832a8421e.png)
* press backspace
* crash

# Traceback
```c++
Thread 1 "fontforge" received signal SIGSEGV, Segmentation fault.
MVTextChanged (mv=0x5555575114b0) at ../fontforgeexe/metricsview.c:1941
1941		if ( *pt!=mv->chars[i]->unicodeenc &&
```
```c++
(gdb) bt
#0  MVTextChanged (mv=0x5555575114b0) at ../fontforgeexe/metricsview.c:1941
#1  0x0000555555773d2f in MV_TextChanged (g=0x555557504cc0, e=0x7fffffffcd50) at ../fontforgeexe/metricsview.c:2111
#2  0x00005555558ab8b0 in GTextFieldChanged (gt=0x555557504cc0, src=-1) at ../gdraw/gtextfield.c:211
#3  0x00005555558b38d3 in gtextfield_key (g=0x555557504cc0, event=0x7fffffffcfe0) at ../gdraw/gtextfield.c:1884
#4  0x0000555555852988 in _GWidget_TopLevel_Key (top=0x555557511730, ew=0x555557511730, event=0x7fffffffcfe0) at ../gdraw/gcontainer.c:491
#5  0x0000555555852fb7 in _GWidget_TopLevel_eh (gw=0x555557511730, event=0x7fffffffcfe0) at ../gdraw/gcontainer.c:607
#6  0x000055555586478f in _GGDKDraw_CallEHChecked (gw=0x555557511730, event=0x7fffffffcfe0, eh=0x555555852d6c <_GWidget_TopLevel_eh>) at ../gdraw/ggdkdraw.c:346
#7  0x00005555558671b2 in _GGDKDraw_DispatchEvent (event=0x555555b93ef0, data=0x555555bab3e0) at ../gdraw/ggdkdraw.c:1249
#8  0x00007ffff6c78a03 in  () at /usr/lib/libgdk-3.so.0
#9  0x00007ffff6cc8a64 in  () at /usr/lib/libgdk-3.so.0
#10 0x00007ffff683bf9c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff688fa49 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff68396f1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#13 0x0000555555869cd4 in GGDKDrawEventLoop (gdisp=0x555555bab3e0) at ../gdraw/ggdkdraw.c:2146
#14 0x00005555558566f4 in GDrawEventLoop (gdisp=0x555555bab3e0) at ../gdraw/gdraw.c:685
#15 0x000055555581ed2a in fontforge_main (argc=2, argv=0x7fffffffe428) at ../fontforgeexe/startui.c:1422
#16 0x00005555555a6ad9 in main (argc=2, argv=0x7fffffffe428) at ../fontforgeexe/main.c:33
```
```c++
(gdb) p/x *pt
$1 = 0x3071
(gdb) p *mv
$2 = {fv = 0x5555563a6690, sf = 0x555556d4dca0, pixelsize = 643, bdf = 0x0, show = 0x555557694450, gw = 0x555557511730, v = 0x555557574f30, font = 0x5555574ed4e0, hsb = 0x5555571378d0, vsb = 0x555555f503e0, mb = 0x555557571000, text = 0x555557504cc0, 
  textPrev = 0x5555573aa6f0, textNext = 0x55555769c470, script = 0x555556d4e810, features = 0x55555756acc0, subtable_list = 0x555557570360, namelab = 0x55555750fe80, widthlab = 0x555557690590, lbearinglab = 0x5555576907a0, rbearinglab = 0x555557693fb0, 
  kernlab = 0x5555576942f0, xstart = 133, width = 3838, height = 879, dwidth = 3803, vwidth = 3670, vheight = 645, mbh = 46, sbh = 35, topend = 102, displayend = 749, fh = 15, as = 12, cmax = 12, clen = 2, chars = 0x555557570510, glyphs = 0x55555792f800, 
  perchar = 0x5555579304b0, sstr = 0x0, mwidth = 60, mbase = 0, glyphcnt = 0, max = 11, pressed_x = 0, pressed_y = 0, activeoff = 0, xoff = 0, coff = 0, yoff = 0, next = 0x0, right_to_left = 0, pressed = 0, pressedwidth = 0, pressedkern = 0, showgrid = 0, antialias = 1, 
  vertical = 0, type = 2, usehinting = 0, pixelsize_set_by_window = 1, xp = 0, yp = 0, ap_owner = 0, ap_start = {x = 0, y = 0}, cursor = 13, scale_index = 4, cur_subtable = 0x5555563d2af0, scriptlangs = 0x55555750e9a0, word_index = 0, layer = 1, fake_unicode_base = 0, 
  gwgic = 0x0, ptsize = 643, dpi = 72, ybaseline = 568, oldscript = 1145457748, oldlang = 1684434036}
(gdb) p mv->chars
$3 = (SplineChar **) 0x555557570510
(gdb) p *mv->chars
$4 = (SplineChar *) 0x0
```

**Comment by jtanx** [comment]
Hmm, I can't seem to repro this
