### ISSUE TITLE
Crash with malformed SFD

### ISSUE THREAD

**Issue by jengelh** [fontforge/fontforge#4786]
Fontforge 20201107 and 20200314 on openSUSE Leap 15.2 x86_64 crash when a specially crafted glyph from a SFD file is about to be displayed in the main window's cell grid.

Trigger file:
[1.sfd.txt](https://github.com/fontforge/fontforge/files/6911950/1.sfd.txt)

gdb crash log:
```
Core was generated by `fontforge 1.sfd'.
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:391
#1  0x00007f8b0953a998 in memcpy (__len=4261412864, __src=<optimized out>, __dest=<optimized out>) at /usr/include/bits/string_fortified.h:29
#2  BdfCFromBitmap (bitmap=bitmap@entry=0x7ffca4ae35c0, bitmap_left=<optimized out>, bitmap_top=<optimized out>, pixelsize=<optimized out>, depth=depth@entry=4, sc=sc@entry=0x5593523cf280, metrics=0x0) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforge/freetype.c:412
#3  0x00007f8b0953c549 in SplineCharFreeTypeRasterizeNoHints (sc=0x5593523cf280, layer=<optimized out>, ptsize=<optimized out>, dpi=<optimized out>, depth=4) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforge/freetype.c:1106
#4  0x00007f8b096727e8 in BDFPieceMeal (bdf=0x559352469df0, index=index@entry=0) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforge/splinefill.c:1700
#5  0x00005593514fcf12 in FVDrawGlyph (pixmap=0x559352451920, fv=0x5593523cf660, index=<optimized out>, forcebg=<optimized out>) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforgeexe/fontview.c:262
#6  0x000055935150b6d0 in FVExpose (fv=fv@entry=0x5593523cf660, pixmap=pixmap@entry=0x559352451920, event=event@entry=0x7ffca4ae45a0) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforgeexe/fontview.c:6014
#7  0x00005593515110f8 in v_e_h (gw=0x559352451920, event=0x7ffca4ae45a0) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforgeexe/fontview.c:6733
#8  0x00005593515bcee7 in _GWidget_Container_eh (gw=0x559352451920, gw@entry=<error reading variable: value has been optimized out>, event=0x7ffca4ae45a0, event@entry=<error reading variable: value has been optimized out>) at /usr/src/debug/fontforge-20201107-1.5.x86_64/gdraw/gcontainer.c:281
```
```
#2  BdfCFromBitmap (bitmap=bitmap@entry=0x7ffca4ae35c0, bitmap_left=<optimized out>, bitmap_top=<optimized out>, pixelsize=<optimized out>, depth=depth@entry=4, sc=sc@entry=0x5593523cf280, metrics=0x0) at /usr/src/debug/fontforge-20201107-1.5.x86_64/fontforge/freetype.c:412
412             memcpy(bdfc->bitmap,bitmap->buffer,bitmap->rows*bdfc->bytes_per_line);
(gdb) p bitmap->rows
$1 = 4261412864  ## this looks wrong
(gdb) l
407         if ( bdfc->bytes_per_line==0 ) bdfc->bytes_per_line = 1;
408         bdfc->bitmap = malloc((bdfc->ymax-bdfc->ymin+1)*bdfc->bytes_per_line);
409         if ( bitmap->rows==0 || bitmap->width==0 )
410             memset(bdfc->bitmap,0,(bdfc->ymax-bdfc->ymin+1)*bdfc->bytes_per_line);
411         else
412             memcpy(bdfc->bitmap,bitmap->buffer,bitmap->rows*bdfc->bytes_per_line);
413         BCCompressBitmap(bdfc);
414         if ( depth!=1 && depth!=8 )
415             BCTruncateToDepth(bdfc,depth);
416     return( bdfc );
```

**Comment by jtanx** [comment]
Is this from a fuzzer?

**Comment by jengelh** [comment]
Negative. This is emitted by [vfontas](https://inai.de/projects/hxtools/) if it can be tricked into making all in-memory glyphs end up having size 0×0. That's something unusual and currently I only see two entry points (e.g. `vfontas -blankfnt -crop 0 0 0 0 -savesfd 1.sfd` after loosening the crop size checks; and `vfontas -loadbdf 1.bdf -savesfd 1.sfd` with a crafted BDF that itself specified ascent=descent=0 and a glyph of size 0×0.)
