### ISSUE TITLE
FF halts when simplifying a glyph

### ISSUE THREAD

**Issue by tersaton** [fontforge/fontforge#5045]
OS: Win 10 and Ubuntu 22.04 LTS
Fontforge version 2022-03-08

I am trying to simplify autotraced glyphs via Element -> Simplify. On some glyphs it works, but on some Fontforge halts immediately after clicking Simplify, and even after waiting half an hour nothing happens. In the end I have to force Fontforge to close. This happens both on Windows and on Ubuntu Linux.

I have included a zipped SFD file with one glyph in it (0 character), that in my tests halts every time.

[test_font_0.zip](https://github.com/fontforge/fontforge/files/8904166/test_font_0.zip)

**Comment by jtanx** [comment]
```
#0  0x00007ffff6560306 in _QuarticSolve (q=0x7fffffffc220, ts=0x7fffffffc460) at ../fontforge/splineutil.c:3533
#1  0x00007ffff6446589 in ApproximateSplineFromPointsSlopes (from=0x60800004dd20, to=0x60800004e020, mid=0x61a000146a80, cnt=28, order2=0, mt=mt_levien) at ../fontforge/splinefit.c:880
#2  0x00007ffff65a2e26 in SplinesRemoveBetweenMaybe (sc=0x613000160dc0, from=0x60800004dd20, to=0x60800004e020, flags=0, err=1) at ../fontforge/splineutil2.c:1307
#3  0x00007ffff65ac587 in SplinePointListSimplify (sc=0x613000160dc0, spl=0x6060000993e0, smpl=0x5555562c92f0 <smpls+48>) at ../fontforge/splineutil2.c:1996
#4  0x00007ffff65ad89b in SplineCharSimplify (sc=0x613000160dc0, head=0x6060000993e0, smpl=0x5555562c92f0 <smpls+48>) at ../fontforge/splineutil2.c:2095
#5  0x00007ffff5f59d8f in _FVSimplify (fv=0x613000164240, smpl=0x5555562c92f0 <smpls+48>) at ../fontforge/fontviewbase.c:1119
#6  0x0000555555a51653 in FVSimplify (fv=0x613000164240, type=0) at ../fontforgeexe/fontview.c:2707
#7  0x0000555555a51685 in FVMenuSimplify (gw=0x6100001a9140, UNUSED_mi=0x6160003b0480, UNUSED_e=0x7fffffffd960) at ../fontforgeexe/fontview.c:2711
#8  0x0000555555e6a46e in gmenu_mouse (m=0x6110000b2c40, event=0x7fffffffd960) at ../gdraw/gmenu.c:759
#9  0x0000555555e6e0c9 in gmenu_eh (w=0x610000211840, ge=0x7fffffffd960) at ../gdraw/gmenu.c:1196
#10 0x0000555555e10cc1 in _GGDKDraw_CallEHChecked (gw=0x610000211840, event=0x7fffffffd960, eh=0x555555e6df66 <gmenu_eh>) at ../gdraw/ggdkdraw.c:347
#11 0x0000555555e19cae in _GGDKDraw_DispatchEvent (event=0x621000054400, data=0x614000000c40) at ../gdraw/ggdkdraw.c:1234
#12 0x00007ffff5210765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#13 0x00007ffff5240f92 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#14 0x00007ffff4543537 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff4543770 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff45437fc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x0000555555e20b29 in GGDKDrawEventLoop (gdisp=0x614000000c40) at ../gdraw/ggdkdraw.c:2131
#18 0x0000555555de9b67 in GDrawEventLoop (gdisp=0x614000000c40) at ../gdraw/gdraw.c:691
#19 0x0000555555d56d57 in fontforge_main (argc=1, argv=0x7fffffffdef8) at ../fontforgeexe/startui.c:1032
#20 0x00005555556ae38a in main (argc=1, argv=0x7fffffffdef8) at ../fontforgeexe/main.c:33
```
