### ISSUE TITLE
Assigning to fontforge.font.bitmapSizes broken/impossible?

### ISSUE THREAD

**Issue by nabijaczleweli** [fontforge/fontforge#5137]
### When reporting a bug/issue:
- [x] Screenshot: 
    ```
    >>> fontforge.font().bitmapSizes = (16, 32, 64, 128)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    SystemError: new style getargs format but argument is not a tuple
    ```
- [x] The FontForge version and the operating system you're using: 8ce3216d492d4a249ffec163c005d098df28e58c on sid (also 1:20201107\~dfsg-4 (bullseye) and 1:20220308\~dfsg-1 (sid))
- [x] The behavior you expect to see, and the actual behavior: as [per spec](https://fontforge.org/docs/scripting/python/fontforge.html#fontforge.font.bitmapSizes): to be able to assign a tuple there, and actually I'm not
- [x] Steps to reproduce the behavior: see p. 1

To ensure I wasn't holding it wrong I also did:
```
>>> fontforge.open('Untitled1.sfdir').bitmapSizes
(16, 32, 64, 128)
>>> fontforge.font().bitmapSizes = (16, 32, 64, 128)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: new style getargs format but argument is not a tuple
>>> fontforge.font().bitmapSizes = fontforge.open('Untitled1.sfdir').bitmapSizes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: new style getargs format but argument is not a tuple
```
so idk.

What may be relevant and what the template doesn't ask for is the Python version: 3.10.6-1 and 3.9.2-3

**Comment by iorsh** [comment]
Fixed by #5138
