### ISSUE TITLE
UnicodeEncodeError when merging otf file with nametable in ttx

### ISSUE THREAD

**Issue by bjg2** [fontforge/fontforge#5340]
Font forge version: 4.29.0
OS: linux (actually, WSL on windows)

For 99.9% of the files, everything works as expected, but for some I get an unexpected error while trying to override name table.

Attached are the font and the ttx override I was trying to merge ([files.zip](https://github.com/fontforge/fontforge/files/13842284/files.zip)), and the command I was trying to execute was: "ttx -m font.otf -o out.otf fix.ttx". Note that "ttx font.otf" works as expected, as well as "ttx fix.ttx". Below is the error output I get:

```
Compiling "fix.ttx" to "out.otf"...
Parsing 'name' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\fontTools\ttx.py", line 405, in main
    process(jobs, options)
  File "C:\Python311\Lib\site-packages\fontTools\ttx.py", line 387, in process
    action(input, output, options)
  File "C:\Python311\Lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\ttx.py", line 305, in ttCompile
    ttf.save(output)
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\ttFont.py", line 181, in save
    writer_reordersTables = self._save(tmp)
                            ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\ttFont.py", line 221, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\ttFont.py", line 630, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\ttFont.py", line 634, in _writeTable
    tabledata = self.getTableData(tag)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\ttFont.py", line 656, in getTableData
    return self.tables[tag].compile(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 19, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 241, in compile
    topCompiler = self.topDictIndex.getCompiler(strings, self, isCFF2=isCFF2)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 799, in getCompiler
    return self.compilerClass(self, strings, parent, isCFF2=isCFF2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 550, in __init__
    self.items = self.getItems(items, strings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 628, in getItems
    out.append(item.getCompiler(strings, self))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 2574, in getCompiler
    return self.compilerClass(self, strings, parent, isCFF2=isCFF2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 2271, in __init__
    value = conv.write(dictObj, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\cffLib\__init__.py", line 1353, in write
    return tobytes(value, encoding='ascii')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fontTools\misc\textTools.py", line 131, in tobytes
    return s.encode(encoding, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode charac
ters in position 0-2: ordinal not in range(128)
```

**Comment by iorsh** [comment]
Font Info --> PS Names --> Name for Humans is "☞ZagLight", and it contains a non-ASCII character. I think this is illegal - see #1481. How did you create font.otf? It doesn't seem FF allows such names

**Comment by iorsh** [comment]
It's a FontForge forum, not FontTools, btw. But you are welcome :)

**Comment by bjg2** [comment]
Thank you very much, I don't know how I managed to write the issue here xD I will go on and open issue in fonttools.

I didn't create font.otf, it was found like that...  Also, I was trying to override name table, whatever it was... And creating font from nametable itself works, so I'm not sure what is the problem when merging with , but all of these are questions for fonttools. :)

Closing this one, opening issue there, thanks for the redirection :) (for reference, https://github.com/fonttools/fonttools/issues/3405)
