### ISSUE TITLE
Fontforge Crashes When Opening a UFO font

### ISSUE THREAD

**Issue by tuldok89** [fontforge/fontforge#5444]
- Fontforge version: Commit 45d74411b2ec9b6060bfa58534c636cc30208f7b
- OS Version: Windows 11 Version 23H2 Build 22631.3737

I was trying to open a UFO font file of an opensource font [0xProto](https://github.com/0xType/0xProto). The program crashes upon opening the UFO file. To reproduce the crash, open either [0xProto-Regular.ufo](https://github.com/0xType/0xProto/tree/main/sources/0xProto-Regular.ufo) or [0xProto-Italic.ufo](https://github.com/0xType/0xProto/tree/main/sources/0xProto-Italic.ufo) from the linked repo above.

Below is the GDB backtrace of the crash

```
#0  0x00007ffe3aed90be in _UFOLoadGlyph (sf=0x75bbbc0, doc=0xd5a5d20,
    glifname=0xd5b1910 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo/glyphs/ringhalfleft.glif",
    glyphname=0xd5af6e0 "ringhalfleft", existingglyph=0x0, layerdest=1)
    at C:/msys64/home/denve/fontforge/fontforge/ufo.c:2724
#1  0x00007ffe3aeda60e in UFOLoadGlyph (sf=0x75bbbc0,
    glifname=0xd5b1910 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo/glyphs/ringhalfleft.glif",
    glyphname=0xd5af6e0 "ringhalfleft", existingglyph=0x0, layerdest=1)
    at C:/msys64/home/denve/fontforge/fontforge/ufo.c:3015
#2  0x00007ffe3aedabdc in UFOLoadGlyphs (sf=0x75bbbc0,
    glyphdir=0x75f97f0 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo/glyphs", layerdest=1)
    at C:/msys64/home/denve/fontforge/fontforge/ufo.c:3109
#3  0x00007ffe3aee0831 in SFReadUFO (basedir=0x7586590 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo",
    flags=0) at C:/msys64/home/denve/fontforge/fontforge/ufo.c:4275
#4  0x00007ffe3adc3459 in _ReadSplineFont (file=0x0,
    filename=0x7586cd0 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo", openflags=0)
    at C:/msys64/home/denve/fontforge/fontforge/splinefont.c:1154
#5  0x00007ffe3adc4b1d in ReadSplineFont (
    filename=0x7586cd0 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo", openflags=0)
    at C:/msys64/home/denve/fontforge/fontforge/splinefont.c:1365
#6  0x00007ffe3adc4d61 in LoadSplineFont (
    filename=0x7587af0 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo", openflags=0)
    at C:/msys64/home/denve/fontforge/fontforge/splinefont.c:1416
#7  0x00007ffe3abe82a9 in ViewPostScriptFont (
    filename=0x7587af0 "C:/msys64/home/denve/0xProto/sources/0xProto-Regular.ufo", openflags=0)
    at C:/msys64/home/denve/fontforge/fontforge/fontviewbase.c:1387
#8  0x00007ff73a523773 in _FVMenuOpen (fv=0x0) at C:/msys64/home/denve/fontforge/fontforgeexe/fontview.c:1292
#9  0x00007ff73a64fa09 in fontforge_main (argc=1, argv=0x70d7c0)
    at C:/msys64/home/denve/fontforge/fontforgeexe/startui.c:1031
#10 0x00007ff73a3d1472 in main (argc=1, argv=0x70d7c0) at C:/msys64/home/denve/fontforge/fontforgeexe/main.c:33
```

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [x] The FontForge version and the operating system you're using
- [x] The behavior you expect to see, and the actual behavior
- [x] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by iorsh** [comment]
The 0xProto repository changed, the UFO font in question is now available at
https://github.com/0xType/0xProto/tree/957808a8f2e4eb641a251de56b6dd27372969518/sources/0xProto-Regular.ufo
